/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.ArNetworking;
import com.mobilerobots.Aria.*;
public class ArClientArg {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  /* for internal use by swig only */
  public ArClientArg(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArClientArg obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ArNetworkingJavaJNI.delete_ArClientArg(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ArClientArg(boolean isDisplayHintParsed, ArPriority.Priority lastPriority) {
    this(ArNetworkingJavaJNI.new_ArClientArg__SWIG_0(isDisplayHintParsed, lastPriority.swigValue()), true);
  }

  public ArClientArg(boolean isDisplayHintParsed) {
    this(ArNetworkingJavaJNI.new_ArClientArg__SWIG_1(isDisplayHintParsed), true);
  }

  public ArClientArg() {
    this(ArNetworkingJavaJNI.new_ArClientArg__SWIG_2(), true);
  }

  public boolean isSendableParamType(ArConfigArg arg) {
    return ArNetworkingJavaJNI.ArClientArg_isSendableParamType(swigCPtr, this, ArConfigArg.getCPtr(arg), arg);
  }

  public boolean createArg(ArNetPacket packet, ArConfigArg argOut) {
    return ArNetworkingJavaJNI.ArClientArg_createArg(swigCPtr, this, ArNetPacket.getCPtr(packet), packet, ArConfigArg.getCPtr(argOut), argOut);
  }

  public boolean createPacket(ArConfigArg arg, ArNetPacket packet) {
    return ArNetworkingJavaJNI.ArClientArg_createPacket(swigCPtr, this, ArConfigArg.getCPtr(arg), arg, ArNetPacket.getCPtr(packet), packet);
  }

  public boolean bufToArgValue(ArNetPacket packet, ArConfigArg arg) {
    return ArNetworkingJavaJNI.ArClientArg_bufToArgValue(swigCPtr, this, ArNetPacket.getCPtr(packet), packet, ArConfigArg.getCPtr(arg), arg);
  }

  public boolean argValueToBuf(ArConfigArg arg, ArNetPacket packet) {
    return ArNetworkingJavaJNI.ArClientArg_argValueToBuf(swigCPtr, this, ArConfigArg.getCPtr(arg), arg, ArNetPacket.getCPtr(packet), packet);
  }

  public boolean argTextToBuf(ArConfigArg arg, ArNetPacket packet) {
    return ArNetworkingJavaJNI.ArClientArg_argTextToBuf(swigCPtr, this, ArConfigArg.getCPtr(arg), arg, ArNetPacket.getCPtr(packet), packet);
  }

}
