/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.ArNetworking;
import com.mobilerobots.Aria.*;
public class ArClientDeleteFileOnServer {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  /* for internal use by swig only */
  public ArClientDeleteFileOnServer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArClientDeleteFileOnServer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ArNetworkingJavaJNI.delete_ArClientDeleteFileOnServer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ArClientDeleteFileOnServer(ArClientBase client) {
    this(ArNetworkingJavaJNI.new_ArClientDeleteFileOnServer(ArClientBase.getCPtr(client), client), true);
  }

  public boolean isAvailable() {
    return ArNetworkingJavaJNI.ArClientDeleteFileOnServer_isAvailable(swigCPtr, this);
  }

  public boolean deleteFileFromDirectory(String directory, String fileName) {
    return ArNetworkingJavaJNI.ArClientDeleteFileOnServer_deleteFileFromDirectory(swigCPtr, this, directory, fileName);
  }

  public boolean isWaitingForReturn() {
    return ArNetworkingJavaJNI.ArClientDeleteFileOnServer_isWaitingForReturn(swigCPtr, this);
  }

  public String getDirectory() {
    return ArNetworkingJavaJNI.ArClientDeleteFileOnServer_getDirectory(swigCPtr, this);
  }

  public String getFileName() {
    return ArNetworkingJavaJNI.ArClientDeleteFileOnServer_getFileName(swigCPtr, this);
  }

  public void addFileDeletedCallback(ArFunctor1_Int functor, ArListPos.Pos position) {
    ArNetworkingJavaJNI.ArClientDeleteFileOnServer_addFileDeletedCallback__SWIG_0(swigCPtr, this, ArFunctor1_Int.getCPtr(functor), functor, position.swigValue());
  }

  public void addFileDeletedCallback(ArFunctor1_Int functor) {
    ArNetworkingJavaJNI.ArClientDeleteFileOnServer_addFileDeletedCallback__SWIG_1(swigCPtr, this, ArFunctor1_Int.getCPtr(functor), functor);
  }

  public void remFileDeletedCallback(ArFunctor1_Int functor) {
    ArNetworkingJavaJNI.ArClientDeleteFileOnServer_remFileDeletedCallback(swigCPtr, this, ArFunctor1_Int.getCPtr(functor), functor);
  }

  public ArTime getLastCompletedSend() {
    return new ArTime(ArNetworkingJavaJNI.ArClientDeleteFileOnServer_getLastCompletedSend(swigCPtr, this), true);
  }

  public ArTime getLastStartedSend() {
    return new ArTime(ArNetworkingJavaJNI.ArClientDeleteFileOnServer_getLastStartedSend(swigCPtr, this), true);
  }

}
