/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.ArNetworking;
import com.mobilerobots.Aria.*;
public class ArClientHandlerConfig {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  /* for internal use by swig only */
  public ArClientHandlerConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArClientHandlerConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ArNetworkingJavaJNI.delete_ArClientHandlerConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ArClientHandlerConfig(ArClientBase client, boolean ignoreBounds, String robotName) {
    this(ArNetworkingJavaJNI.new_ArClientHandlerConfig__SWIG_0(ArClientBase.getCPtr(client), client, ignoreBounds, robotName), true);
  }

  public ArClientHandlerConfig(ArClientBase client, boolean ignoreBounds) {
    this(ArNetworkingJavaJNI.new_ArClientHandlerConfig__SWIG_1(ArClientBase.getCPtr(client), client, ignoreBounds), true);
  }

  public ArClientHandlerConfig(ArClientBase client) {
    this(ArNetworkingJavaJNI.new_ArClientHandlerConfig__SWIG_2(ArClientBase.getCPtr(client), client), true);
  }

  public void requestConfigFromServer() {
    ArNetworkingJavaJNI.ArClientHandlerConfig_requestConfigFromServer(swigCPtr, this);
  }

  public void reloadConfigOnServer() {
    ArNetworkingJavaJNI.ArClientHandlerConfig_reloadConfigOnServer(swigCPtr, this);
  }

  public ArConfig getConfigCopy() {
    return new ArConfig(ArNetworkingJavaJNI.ArClientHandlerConfig_getConfigCopy(swigCPtr, this), true);
  }

  public void addGotConfigCB(ArFunctor functor, ArListPos.Pos position) {
    ArNetworkingJavaJNI.ArClientHandlerConfig_addGotConfigCB__SWIG_0(swigCPtr, this, ArFunctor.getCPtr(functor), functor, position.swigValue());
  }

  public void addGotConfigCB(ArFunctor functor) {
    ArNetworkingJavaJNI.ArClientHandlerConfig_addGotConfigCB__SWIG_1(swigCPtr, this, ArFunctor.getCPtr(functor), functor);
  }

  public void remGotConfigCB(ArFunctor functor) {
    ArNetworkingJavaJNI.ArClientHandlerConfig_remGotConfigCB(swigCPtr, this, ArFunctor.getCPtr(functor), functor);
  }

  public void addSaveConfigSucceededCB(ArFunctor functor, ArListPos.Pos position) {
    ArNetworkingJavaJNI.ArClientHandlerConfig_addSaveConfigSucceededCB__SWIG_0(swigCPtr, this, ArFunctor.getCPtr(functor), functor, position.swigValue());
  }

  public void addSaveConfigSucceededCB(ArFunctor functor) {
    ArNetworkingJavaJNI.ArClientHandlerConfig_addSaveConfigSucceededCB__SWIG_1(swigCPtr, this, ArFunctor.getCPtr(functor), functor);
  }

  public void remSaveConfigSucceededCB(ArFunctor functor) {
    ArNetworkingJavaJNI.ArClientHandlerConfig_remSaveConfigSucceededCB(swigCPtr, this, ArFunctor.getCPtr(functor), functor);
  }

  public void addSaveConfigFailedCB(ArFunctor1_CString functor, ArListPos.Pos position) {
    ArNetworkingJavaJNI.ArClientHandlerConfig_addSaveConfigFailedCB__SWIG_0(swigCPtr, this, ArFunctor1_CString.getCPtr(functor), functor, position.swigValue());
  }

  public void addSaveConfigFailedCB(ArFunctor1_CString functor) {
    ArNetworkingJavaJNI.ArClientHandlerConfig_addSaveConfigFailedCB__SWIG_1(swigCPtr, this, ArFunctor1_CString.getCPtr(functor), functor);
  }

  public void remSaveConfigFailedCB(ArFunctor1_CString functor) {
    ArNetworkingJavaJNI.ArClientHandlerConfig_remSaveConfigFailedCB(swigCPtr, this, ArFunctor1_CString.getCPtr(functor), functor);
  }

  public boolean haveGottenConfig() {
    return ArNetworkingJavaJNI.ArClientHandlerConfig_haveGottenConfig(swigCPtr, this);
  }

  public void saveConfigToServer() {
    ArNetworkingJavaJNI.ArClientHandlerConfig_saveConfigToServer__SWIG_0(swigCPtr, this);
  }

  public void saveConfigToServer(ArConfig config, SWIGTYPE_p_std__setT_std__string_ArStrCaseCmpOp_t ignoreTheseSections) {
    ArNetworkingJavaJNI.ArClientHandlerConfig_saveConfigToServer__SWIG_1(swigCPtr, this, ArConfig.getCPtr(config), config, SWIGTYPE_p_std__setT_std__string_ArStrCaseCmpOp_t.getCPtr(ignoreTheseSections));
  }

  public void saveConfigToServer(ArConfig config) {
    ArNetworkingJavaJNI.ArClientHandlerConfig_saveConfigToServer__SWIG_2(swigCPtr, this, ArConfig.getCPtr(config), config);
  }

  public boolean haveRequestedDefaults() {
    return ArNetworkingJavaJNI.ArClientHandlerConfig_haveRequestedDefaults(swigCPtr, this);
  }

  public boolean haveGottenDefaults() {
    return ArNetworkingJavaJNI.ArClientHandlerConfig_haveGottenDefaults(swigCPtr, this);
  }

  public boolean canRequestDefaults() {
    return ArNetworkingJavaJNI.ArClientHandlerConfig_canRequestDefaults(swigCPtr, this);
  }

  public boolean requestDefaultConfigFromServer() {
    return ArNetworkingJavaJNI.ArClientHandlerConfig_requestDefaultConfigFromServer(swigCPtr, this);
  }

  public ArConfig getDefaultConfig() {
    long cPtr = ArNetworkingJavaJNI.ArClientHandlerConfig_getDefaultConfig(swigCPtr, this);
    return (cPtr == 0) ? null : new ArConfig(cPtr, false);
  }

  public boolean requestConfigDefaults() {
    return ArNetworkingJavaJNI.ArClientHandlerConfig_requestConfigDefaults(swigCPtr, this);
  }

  public boolean requestSectionDefaults(String section) {
    return ArNetworkingJavaJNI.ArClientHandlerConfig_requestSectionDefaults(swigCPtr, this, section);
  }

  public void addGotConfigDefaultsCB(ArFunctor functor, ArListPos.Pos position) {
    ArNetworkingJavaJNI.ArClientHandlerConfig_addGotConfigDefaultsCB__SWIG_0(swigCPtr, this, ArFunctor.getCPtr(functor), functor, position.swigValue());
  }

  public void addGotConfigDefaultsCB(ArFunctor functor) {
    ArNetworkingJavaJNI.ArClientHandlerConfig_addGotConfigDefaultsCB__SWIG_1(swigCPtr, this, ArFunctor.getCPtr(functor), functor);
  }

  public void remGotConfigDefaultsCB(ArFunctor functor) {
    ArNetworkingJavaJNI.ArClientHandlerConfig_remGotConfigDefaultsCB(swigCPtr, this, ArFunctor.getCPtr(functor), functor);
  }

  public ArConfig getConfig() {
    long cPtr = ArNetworkingJavaJNI.ArClientHandlerConfig_getConfig(swigCPtr, this);
    return (cPtr == 0) ? null : new ArConfig(cPtr, false);
  }

  public int lock() {
    return ArNetworkingJavaJNI.ArClientHandlerConfig_lock(swigCPtr, this);
  }

  public int tryLock() {
    return ArNetworkingJavaJNI.ArClientHandlerConfig_tryLock(swigCPtr, this);
  }

  public int unlock() {
    return ArNetworkingJavaJNI.ArClientHandlerConfig_unlock(swigCPtr, this);
  }

  public void setQuiet(boolean isQuiet) {
    ArNetworkingJavaJNI.ArClientHandlerConfig_setQuiet(swigCPtr, this, isQuiet);
  }

  public void handleGetConfigBySections(ArNetPacket packet) {
    ArNetworkingJavaJNI.ArClientHandlerConfig_handleGetConfigBySections(swigCPtr, this, ArNetPacket.getCPtr(packet), packet);
  }

  public void handleGetConfigSectionFlags(ArNetPacket packet) {
    ArNetworkingJavaJNI.ArClientHandlerConfig_handleGetConfigSectionFlags(swigCPtr, this, ArNetPacket.getCPtr(packet), packet);
  }

  public void handleGetConfig(ArNetPacket packet) {
    ArNetworkingJavaJNI.ArClientHandlerConfig_handleGetConfig(swigCPtr, this, ArNetPacket.getCPtr(packet), packet);
  }

  public void handleSetConfig(ArNetPacket packet) {
    ArNetworkingJavaJNI.ArClientHandlerConfig_handleSetConfig(swigCPtr, this, ArNetPacket.getCPtr(packet), packet);
  }

  public void handleGetConfigDefaults(ArNetPacket packet) {
    ArNetworkingJavaJNI.ArClientHandlerConfig_handleGetConfigDefaults(swigCPtr, this, ArNetPacket.getCPtr(packet), packet);
  }

}
