/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.ArNetworking;
import com.mobilerobots.Aria.*;
public class ArClientFileFromClient {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  /* for internal use by swig only */
  public ArClientFileFromClient(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArClientFileFromClient obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ArNetworkingJavaJNI.delete_ArClientFileFromClient(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ArClientFileFromClient(ArClientBase client) {
    this(ArNetworkingJavaJNI.new_ArClientFileFromClient(ArClientBase.getCPtr(client), client), true);
  }

  public boolean isAvailable() {
    return ArNetworkingJavaJNI.ArClientFileFromClient_isAvailable(swigCPtr, this);
  }

  public boolean isAvailableSlow() {
    return ArNetworkingJavaJNI.ArClientFileFromClient_isAvailableSlow(swigCPtr, this);
  }

  public boolean isAvailableFast() {
    return ArNetworkingJavaJNI.ArClientFileFromClient_isAvailableFast(swigCPtr, this);
  }

  public boolean isAvailableSetTimestamp() {
    return ArNetworkingJavaJNI.ArClientFileFromClient_isAvailableSetTimestamp(swigCPtr, this);
  }

  public boolean putFileToDirectory(String directory, String fileName, String clientFileName, ArClientFileFromClient.SendSpeed sendSpeed, boolean isSetTimestamp) {
    return ArNetworkingJavaJNI.ArClientFileFromClient_putFileToDirectory__SWIG_0(swigCPtr, this, directory, fileName, clientFileName, sendSpeed.swigValue(), isSetTimestamp);
  }

  public boolean putFileToDirectory(String directory, String fileName, String clientFileName, ArClientFileFromClient.SendSpeed sendSpeed) {
    return ArNetworkingJavaJNI.ArClientFileFromClient_putFileToDirectory__SWIG_1(swigCPtr, this, directory, fileName, clientFileName, sendSpeed.swigValue());
  }

  public boolean putFileToDirectory(String directory, String fileName, String clientFileName) {
    return ArNetworkingJavaJNI.ArClientFileFromClient_putFileToDirectory__SWIG_2(swigCPtr, this, directory, fileName, clientFileName);
  }

  public void cancelPut() {
    ArNetworkingJavaJNI.ArClientFileFromClient_cancelPut(swigCPtr, this);
  }

  public boolean isWaitingForReturn() {
    return ArNetworkingJavaJNI.ArClientFileFromClient_isWaitingForReturn(swigCPtr, this);
  }

  public String getDirectory() {
    return ArNetworkingJavaJNI.ArClientFileFromClient_getDirectory(swigCPtr, this);
  }

  public String getFileName() {
    return ArNetworkingJavaJNI.ArClientFileFromClient_getFileName(swigCPtr, this);
  }

  public String getClientFileName() {
    return ArNetworkingJavaJNI.ArClientFileFromClient_getClientFileName(swigCPtr, this);
  }

  public void addFileSentCallback(ArFunctor1_Int functor, ArListPos.Pos position) {
    ArNetworkingJavaJNI.ArClientFileFromClient_addFileSentCallback__SWIG_0(swigCPtr, this, ArFunctor1_Int.getCPtr(functor), functor, position.swigValue());
  }

  public void addFileSentCallback(ArFunctor1_Int functor) {
    ArNetworkingJavaJNI.ArClientFileFromClient_addFileSentCallback__SWIG_1(swigCPtr, this, ArFunctor1_Int.getCPtr(functor), functor);
  }

  public void remFileSentCallback(ArFunctor1_Int functor) {
    ArNetworkingJavaJNI.ArClientFileFromClient_remFileSentCallback(swigCPtr, this, ArFunctor1_Int.getCPtr(functor), functor);
  }

  public ArTime getLastCompletedSend() {
    return new ArTime(ArNetworkingJavaJNI.ArClientFileFromClient_getLastCompletedSend(swigCPtr, this), true);
  }

  public ArTime getLastStartedSend() {
    return new ArTime(ArNetworkingJavaJNI.ArClientFileFromClient_getLastStartedSend(swigCPtr, this), true);
  }

  public final static class SendSpeed {
    public final static SendSpeed SPEED_AUTO = new SendSpeed("SPEED_AUTO");
    public final static SendSpeed SPEED_FAST = new SendSpeed("SPEED_FAST");
    public final static SendSpeed SPEED_SLOW = new SendSpeed("SPEED_SLOW");

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static SendSpeed swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + SendSpeed.class + " with value " + swigValue);
    }

    private SendSpeed(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private SendSpeed(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private SendSpeed(String swigName, SendSpeed swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static SendSpeed[] swigValues = { SPEED_AUTO, SPEED_FAST, SPEED_SLOW };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
