/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.ArNetworking;
import com.mobilerobots.Aria.*;
public class ArClientFileListerItem {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  /* for internal use by swig only */
  public ArClientFileListerItem(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArClientFileListerItem obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ArNetworkingJavaJNI.delete_ArClientFileListerItem(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ArClientFileListerItem(String name, SWIGTYPE_p_time_t atime, SWIGTYPE_p_time_t mtime, long size) {
    this(ArNetworkingJavaJNI.new_ArClientFileListerItem__SWIG_0(name, SWIGTYPE_p_time_t.getCPtr(atime), SWIGTYPE_p_time_t.getCPtr(mtime), size), true);
  }

  public ArClientFileListerItem(ArClientFileListerItem item) {
    this(ArNetworkingJavaJNI.new_ArClientFileListerItem__SWIG_1(ArClientFileListerItem.getCPtr(item), item), true);
  }

  public String getName() {
    return ArNetworkingJavaJNI.ArClientFileListerItem_getName(swigCPtr, this);
  }

  public SWIGTYPE_p_time_t getLastAccessedTime() {
    return new SWIGTYPE_p_time_t(ArNetworkingJavaJNI.ArClientFileListerItem_getLastAccessedTime(swigCPtr, this), true);
  }

  public SWIGTYPE_p_time_t getLastModifiedTime() {
    return new SWIGTYPE_p_time_t(ArNetworkingJavaJNI.ArClientFileListerItem_getLastModifiedTime(swigCPtr, this), true);
  }

  public long getSize() {
    return ArNetworkingJavaJNI.ArClientFileListerItem_getSize(swigCPtr, this);
  }

}
