/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.ArNetworking;
import com.mobilerobots.Aria.*;
public class ArClientSimpleConnector {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  /* for internal use by swig only */
  public ArClientSimpleConnector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArClientSimpleConnector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ArNetworkingJavaJNI.delete_ArClientSimpleConnector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ArClientSimpleConnector(ArArgumentParser parser) {
    this(ArNetworkingJavaJNI.new_ArClientSimpleConnector__SWIG_0(ArArgumentParser.getCPtr(parser), parser), true);
  }

  public ArClientSimpleConnector(java.lang.String[] argc) {
    this(ArNetworkingJavaJNI.new_ArClientSimpleConnector__SWIG_1(argc), true);
  }

  public ArClientSimpleConnector(ArArgumentBuilder arguments) {
    this(ArNetworkingJavaJNI.new_ArClientSimpleConnector__SWIG_2(ArArgumentBuilder.getCPtr(arguments), arguments), true);
  }

  public boolean connectClient(ArClientBase client, boolean print) {
    return ArNetworkingJavaJNI.ArClientSimpleConnector_connectClient__SWIG_0(swigCPtr, this, ArClientBase.getCPtr(client), client, print);
  }

  public boolean connectClient(ArClientBase client) {
    return ArNetworkingJavaJNI.ArClientSimpleConnector_connectClient__SWIG_1(swigCPtr, this, ArClientBase.getCPtr(client), client);
  }

  public boolean parseArgs() {
    return ArNetworkingJavaJNI.ArClientSimpleConnector_parseArgs__SWIG_0(swigCPtr, this);
  }

  public boolean parseArgs(ArArgumentParser parser) {
    return ArNetworkingJavaJNI.ArClientSimpleConnector_parseArgs__SWIG_1(swigCPtr, this, ArArgumentParser.getCPtr(parser), parser);
  }

  public void logOptions() {
    ArNetworkingJavaJNI.ArClientSimpleConnector_logOptions(swigCPtr, this);
  }

}
