/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.ArNetworking;
import com.mobilerobots.Aria.*;
public class ArClientCommands {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  /* for internal use by swig only */
  public ArClientCommands(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArClientCommands obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ArNetworkingJavaJNI.delete_ArClientCommands(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ArClientCommands() {
    this(ArNetworkingJavaJNI.new_ArClientCommands(), true);
  }

  public final static class ClientCommands {
    public final static ClientCommands SHUTDOWN = new ClientCommands("SHUTDOWN", ArNetworkingJavaJNI.ArClientCommands_SHUTDOWN_get());
    public final static ClientCommands INTRODUCTION = new ClientCommands("INTRODUCTION", ArNetworkingJavaJNI.ArClientCommands_INTRODUCTION_get());
    public final static ClientCommands UDP_INTRODUCTION = new ClientCommands("UDP_INTRODUCTION", ArNetworkingJavaJNI.ArClientCommands_UDP_INTRODUCTION_get());
    public final static ClientCommands UDP_CONFIRMATION = new ClientCommands("UDP_CONFIRMATION", ArNetworkingJavaJNI.ArClientCommands_UDP_CONFIRMATION_get());
    public final static ClientCommands TCP_ONLY = new ClientCommands("TCP_ONLY", ArNetworkingJavaJNI.ArClientCommands_TCP_ONLY_get());
    public final static ClientCommands LIST = new ClientCommands("LIST", ArNetworkingJavaJNI.ArClientCommands_LIST_get());
    public final static ClientCommands REQUEST = new ClientCommands("REQUEST", ArNetworkingJavaJNI.ArClientCommands_REQUEST_get());
    public final static ClientCommands REQUESTSTOP = new ClientCommands("REQUESTSTOP", ArNetworkingJavaJNI.ArClientCommands_REQUESTSTOP_get());

    public final int swigValue() {
      return swigValue;
    }

    public String toString() {
      return swigName;
    }

    public static ClientCommands swigToEnum(int swigValue) {
      if (swigValue < swigValues.length && swigValue >= 0 && swigValues[swigValue].swigValue == swigValue)
        return swigValues[swigValue];
      for (int i = 0; i < swigValues.length; i++)
        if (swigValues[i].swigValue == swigValue)
          return swigValues[i];
      throw new IllegalArgumentException("No enum " + ClientCommands.class + " with value " + swigValue);
    }

    private ClientCommands(String swigName) {
      this.swigName = swigName;
      this.swigValue = swigNext++;
    }

    private ClientCommands(String swigName, int swigValue) {
      this.swigName = swigName;
      this.swigValue = swigValue;
      swigNext = swigValue+1;
    }

    private ClientCommands(String swigName, ClientCommands swigEnum) {
      this.swigName = swigName;
      this.swigValue = swigEnum.swigValue;
      swigNext = this.swigValue+1;
    }

    private static ClientCommands[] swigValues = { SHUTDOWN, INTRODUCTION, UDP_INTRODUCTION, UDP_CONFIRMATION, TCP_ONLY, LIST, REQUEST, REQUESTSTOP };
    private static int swigNext = 0;
    private final int swigValue;
    private final String swigName;
  }

}
