/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.ArNetworking;
import com.mobilerobots.Aria.*;
public class ArFunctor_ServerData extends ArFunctor_ServerClient {
  private long swigCPtr;

  /* for internal use by swig only */
  public ArFunctor_ServerData(long cPtr, boolean cMemoryOwn) {
    super(ArNetworkingJavaJNI.SWIGArFunctor_ServerDataUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArFunctor_ServerData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ArNetworkingJavaJNI.delete_ArFunctor_ServerData(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    ArNetworkingJavaJNI.ArFunctor_ServerData_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    ArNetworkingJavaJNI.ArFunctor_ServerData_change_ownership(this, swigCPtr, true);
  }

  public void invoke() {
    ArNetworkingJavaJNI.ArFunctor_ServerData_invoke__SWIG_0(swigCPtr, this);
  }

  public void invoke(ArServerClient p1) {
    ArNetworkingJavaJNI.ArFunctor_ServerData_invoke__SWIG_1(swigCPtr, this, ArServerClient.getCPtr(p1), p1);
  }

  public void invoke(ArServerClient p1, ArNetPacket p2) {
    ArNetworkingJavaJNI.ArFunctor_ServerData_invoke__SWIG_2(swigCPtr, this, ArServerClient.getCPtr(p1), p1, ArNetPacket.getCPtr(p2), p2);
  }

  public ArFunctor_ServerData() {
    this(ArNetworkingJavaJNI.new_ArFunctor_ServerData(), true);
    ArNetworkingJavaJNI.ArFunctor_ServerData_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
