/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.ArNetworking;
import com.mobilerobots.Aria.*; 
public interface ArNetworkingJavaConstants {
  public final static int SWIG_IMPORTED_ARIA = ArNetworkingJavaJNI.SWIG_IMPORTED_ARIA_get();
}
