/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.ArNetworking;
import com.mobilerobots.Aria.*;
public class ArNetPacketSenderTcp {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  /* for internal use by swig only */
  public ArNetPacketSenderTcp(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArNetPacketSenderTcp obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ArNetworkingJavaJNI.delete_ArNetPacketSenderTcp(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ArNetPacketSenderTcp() {
    this(ArNetworkingJavaJNI.new_ArNetPacketSenderTcp(), true);
  }

  public void setSocket(ArSocket socket) {
    ArNetworkingJavaJNI.ArNetPacketSenderTcp_setSocket(swigCPtr, this, ArSocket.getCPtr(socket), socket);
  }

  public ArSocket getSocket() {
    long cPtr = ArNetworkingJavaJNI.ArNetPacketSenderTcp_getSocket(swigCPtr, this);
    return (cPtr == 0) ? null : new ArSocket(cPtr, false);
  }

  public void setBackupTimeout(double connectionTimeoutInMins) {
    ArNetworkingJavaJNI.ArNetPacketSenderTcp_setBackupTimeout(swigCPtr, this, connectionTimeoutInMins);
  }

  public void setDebugLogging(boolean debugLogging) {
    ArNetworkingJavaJNI.ArNetPacketSenderTcp_setDebugLogging(swigCPtr, this, debugLogging);
  }

  public void setLoggingPrefix(String prefix) {
    ArNetworkingJavaJNI.ArNetPacketSenderTcp_setLoggingPrefix(swigCPtr, this, prefix);
  }

  public void sendPacket(ArNetPacket packet, String loggingString) {
    ArNetworkingJavaJNI.ArNetPacketSenderTcp_sendPacket__SWIG_0(swigCPtr, this, ArNetPacket.getCPtr(packet), packet, loggingString);
  }

  public void sendPacket(ArNetPacket packet) {
    ArNetworkingJavaJNI.ArNetPacketSenderTcp_sendPacket__SWIG_1(swigCPtr, this, ArNetPacket.getCPtr(packet), packet);
  }

  public boolean sendData() {
    return ArNetworkingJavaJNI.ArNetPacketSenderTcp_sendData(swigCPtr, this);
  }

}
