/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.ArNetworking;
import com.mobilerobots.Aria.*;
public class ArServerSimpleComUC {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  /* for internal use by swig only */
  public ArServerSimpleComUC(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArServerSimpleComUC obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ArNetworkingJavaJNI.delete_ArServerSimpleComUC(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ArServerSimpleComUC(ArServerHandlerCommands handlerCommands, ArRobot robot) {
    this(ArNetworkingJavaJNI.new_ArServerSimpleComUC(ArServerHandlerCommands.getCPtr(handlerCommands), handlerCommands, ArRobot.getCPtr(robot), robot), true);
  }

  public void command(ArArgumentBuilder arg) {
    ArNetworkingJavaJNI.ArServerSimpleComUC_command(swigCPtr, this, ArArgumentBuilder.getCPtr(arg), arg);
  }

  public void motionCommand(ArArgumentBuilder arg) {
    ArNetworkingJavaJNI.ArServerSimpleComUC_motionCommand(swigCPtr, this, ArArgumentBuilder.getCPtr(arg), arg);
  }

}
