/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.ArNetworking;
import com.mobilerobots.Aria.*;
public class ArServerSimpleComLogRobotConfig {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  /* for internal use by swig only */
  public ArServerSimpleComLogRobotConfig(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArServerSimpleComLogRobotConfig obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ArNetworkingJavaJNI.delete_ArServerSimpleComLogRobotConfig(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ArServerSimpleComLogRobotConfig(ArServerHandlerCommands commands, ArRobot robot, SWIGTYPE_p_ArServerHandlerPopup popupHandler) {
    this(ArNetworkingJavaJNI.new_ArServerSimpleComLogRobotConfig__SWIG_0(ArServerHandlerCommands.getCPtr(commands), commands, ArRobot.getCPtr(robot), robot, SWIGTYPE_p_ArServerHandlerPopup.getCPtr(popupHandler)), true);
  }

  public ArServerSimpleComLogRobotConfig(ArServerHandlerCommands commands, ArRobot robot) {
    this(ArNetworkingJavaJNI.new_ArServerSimpleComLogRobotConfig__SWIG_1(ArServerHandlerCommands.getCPtr(commands), commands, ArRobot.getCPtr(robot), robot), true);
  }

  public void logConfig() {
    ArNetworkingJavaJNI.ArServerSimpleComLogRobotConfig_logConfig(swigCPtr, this);
  }

  public void logMovementConfig() {
    ArNetworkingJavaJNI.ArServerSimpleComLogRobotConfig_logMovementConfig(swigCPtr, this);
  }

  public void logOrigConfig() {
    ArNetworkingJavaJNI.ArServerSimpleComLogRobotConfig_logOrigConfig(swigCPtr, this);
  }

  public void popupConfig() {
    ArNetworkingJavaJNI.ArServerSimpleComLogRobotConfig_popupConfig(swigCPtr, this);
  }

  public void popupOrigConfig() {
    ArNetworkingJavaJNI.ArServerSimpleComLogRobotConfig_popupOrigConfig(swigCPtr, this);
  }

  public void popupMovementConfig() {
    ArNetworkingJavaJNI.ArServerSimpleComLogRobotConfig_popupMovementConfig(swigCPtr, this);
  }

}
