/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.ArNetworking;
import com.mobilerobots.Aria.*;
public class ArServerSimpleComMovementLogging {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  /* for internal use by swig only */
  public ArServerSimpleComMovementLogging(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArServerSimpleComMovementLogging obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ArNetworkingJavaJNI.delete_ArServerSimpleComMovementLogging(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ArServerSimpleComMovementLogging(ArServerHandlerCommands handlerCommands, ArRobot robot, SWIGTYPE_p_ArServerHandlerPopup popupHandler) {
    this(ArNetworkingJavaJNI.new_ArServerSimpleComMovementLogging__SWIG_0(ArServerHandlerCommands.getCPtr(handlerCommands), handlerCommands, ArRobot.getCPtr(robot), robot, SWIGTYPE_p_ArServerHandlerPopup.getCPtr(popupHandler)), true);
  }

  public ArServerSimpleComMovementLogging(ArServerHandlerCommands handlerCommands, ArRobot robot) {
    this(ArNetworkingJavaJNI.new_ArServerSimpleComMovementLogging__SWIG_1(ArServerHandlerCommands.getCPtr(handlerCommands), handlerCommands, ArRobot.getCPtr(robot), robot), true);
  }

  public void logMovementSentEnable() {
    ArNetworkingJavaJNI.ArServerSimpleComMovementLogging_logMovementSentEnable(swigCPtr, this);
  }

  public void logMovementSentDisable() {
    ArNetworkingJavaJNI.ArServerSimpleComMovementLogging_logMovementSentDisable(swigCPtr, this);
  }

  public void logMovementReceivedEnable() {
    ArNetworkingJavaJNI.ArServerSimpleComMovementLogging_logMovementReceivedEnable(swigCPtr, this);
  }

  public void logMovementReceivedDisable() {
    ArNetworkingJavaJNI.ArServerSimpleComMovementLogging_logMovementReceivedDisable(swigCPtr, this);
  }

  public void logVelocitiesReceivedEnable() {
    ArNetworkingJavaJNI.ArServerSimpleComMovementLogging_logVelocitiesReceivedEnable(swigCPtr, this);
  }

  public void logVelocitiesReceivedDisable() {
    ArNetworkingJavaJNI.ArServerSimpleComMovementLogging_logVelocitiesReceivedDisable(swigCPtr, this);
  }

  public void packetsReceivedTrackingEnable() {
    ArNetworkingJavaJNI.ArServerSimpleComMovementLogging_packetsReceivedTrackingEnable(swigCPtr, this);
  }

  public void packetsReceivedTrackingDisable() {
    ArNetworkingJavaJNI.ArServerSimpleComMovementLogging_packetsReceivedTrackingDisable(swigCPtr, this);
  }

  public void packetsSentTrackingEnable() {
    ArNetworkingJavaJNI.ArServerSimpleComMovementLogging_packetsSentTrackingEnable(swigCPtr, this);
  }

  public void packetsSentTrackingDisable() {
    ArNetworkingJavaJNI.ArServerSimpleComMovementLogging_packetsSentTrackingDisable(swigCPtr, this);
  }

  public void logActionsEnable() {
    ArNetworkingJavaJNI.ArServerSimpleComMovementLogging_logActionsEnable(swigCPtr, this);
  }

  public void logActionsDisable() {
    ArNetworkingJavaJNI.ArServerSimpleComMovementLogging_logActionsDisable(swigCPtr, this);
  }

  public void logActions() {
    ArNetworkingJavaJNI.ArServerSimpleComMovementLogging_logActions(swigCPtr, this);
  }

  public void popupMovementParams() {
    ArNetworkingJavaJNI.ArServerSimpleComMovementLogging_popupMovementParams(swigCPtr, this);
  }

  public void resetOdometer() {
    ArNetworkingJavaJNI.ArServerSimpleComMovementLogging_resetOdometer(swigCPtr, this);
  }

}
