/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.ArNetworking;
import com.mobilerobots.Aria.*;
public class ArServerInfoRobot {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  /* for internal use by swig only */
  public ArServerInfoRobot(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArServerInfoRobot obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ArNetworkingJavaJNI.delete_ArServerInfoRobot(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ArServerInfoRobot(ArServerBase server, ArRobot robot) {
    this(ArNetworkingJavaJNI.new_ArServerInfoRobot(ArServerBase.getCPtr(server), server, ArRobot.getCPtr(robot), robot), true);
  }

  public void update(ArServerClient client, ArNetPacket packet) {
    ArNetworkingJavaJNI.ArServerInfoRobot_update(swigCPtr, this, ArServerClient.getCPtr(client), client, ArNetPacket.getCPtr(packet), packet);
  }

  public void updateNumbers(ArServerClient client, ArNetPacket packet) {
    ArNetworkingJavaJNI.ArServerInfoRobot_updateNumbers(swigCPtr, this, ArServerClient.getCPtr(client), client, ArNetPacket.getCPtr(packet), packet);
  }

  public void updateStrings(ArServerClient client, ArNetPacket packet) {
    ArNetworkingJavaJNI.ArServerInfoRobot_updateStrings(swigCPtr, this, ArServerClient.getCPtr(client), client, ArNetPacket.getCPtr(packet), packet);
  }

  public void batteryInfo(ArServerClient client, ArNetPacket packet) {
    ArNetworkingJavaJNI.ArServerInfoRobot_batteryInfo(swigCPtr, this, ArServerClient.getCPtr(client), client, ArNetPacket.getCPtr(packet), packet);
  }

  public void physicalInfo(ArServerClient client, ArNetPacket packet) {
    ArNetworkingJavaJNI.ArServerInfoRobot_physicalInfo(swigCPtr, this, ArServerClient.getCPtr(client), client, ArNetPacket.getCPtr(packet), packet);
  }

  public void activityTimeInfo(ArServerClient client, ArNetPacket packet) {
    ArNetworkingJavaJNI.ArServerInfoRobot_activityTimeInfo(swigCPtr, this, ArServerClient.getCPtr(client), client, ArNetPacket.getCPtr(packet), packet);
  }

}
