/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.ArNetworking;
import com.mobilerobots.Aria.*;
public class ArServerInfoSensor {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  /* for internal use by swig only */
  public ArServerInfoSensor(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArServerInfoSensor obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ArNetworkingJavaJNI.delete_ArServerInfoSensor(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ArServerInfoSensor(ArServerBase server, ArRobot robot) {
    this(ArNetworkingJavaJNI.new_ArServerInfoSensor(ArServerBase.getCPtr(server), server, ArRobot.getCPtr(robot), robot), true);
  }

  public void getSensorList(ArServerClient client, ArNetPacket packet) {
    ArNetworkingJavaJNI.ArServerInfoSensor_getSensorList(swigCPtr, this, ArServerClient.getCPtr(client), client, ArNetPacket.getCPtr(packet), packet);
  }

  public void getSensorCurrent(ArServerClient client, ArNetPacket packet) {
    ArNetworkingJavaJNI.ArServerInfoSensor_getSensorCurrent(swigCPtr, this, ArServerClient.getCPtr(client), client, ArNetPacket.getCPtr(packet), packet);
  }

  public void getSensorCumulative(ArServerClient client, ArNetPacket packet) {
    ArNetworkingJavaJNI.ArServerInfoSensor_getSensorCumulative(swigCPtr, this, ArServerClient.getCPtr(client), client, ArNetPacket.getCPtr(packet), packet);
  }

}
