/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.ArNetworking;
import com.mobilerobots.Aria.*;
public class ArServerModeIdle extends ArServerMode {
  private long swigCPtr;

  /* for internal use by swig only */
  public ArServerModeIdle(long cPtr, boolean cMemoryOwn) {
    super(ArNetworkingJavaJNI.SWIGArServerModeIdleUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArServerModeIdle obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ArNetworkingJavaJNI.delete_ArServerModeIdle(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ArServerModeIdle(ArServerBase server, ArRobot robot) {
    this(ArNetworkingJavaJNI.new_ArServerModeIdle(ArServerBase.getCPtr(server), server, ArRobot.getCPtr(robot), robot), true);
  }

  public void activate() {
    ArNetworkingJavaJNI.ArServerModeIdle_activate(swigCPtr, this);
  }

  public void deactivate() {
    ArNetworkingJavaJNI.ArServerModeIdle_deactivate(swigCPtr, this);
  }

  public void userTask() {
    ArNetworkingJavaJNI.ArServerModeIdle_userTask(swigCPtr, this);
  }

  public void setModeInterrupted(ArServerMode modeInterrupted) {
    ArNetworkingJavaJNI.ArServerModeIdle_setModeInterrupted(swigCPtr, this, ArServerMode.getCPtr(modeInterrupted), modeInterrupted);
  }

  public ArServerMode getModeInterrupted() {
    long cPtr = ArNetworkingJavaJNI.ArServerModeIdle_getModeInterrupted(swigCPtr, this);
    return (cPtr == 0) ? null : new ArServerMode(cPtr, false);
  }

  public ArActionGroup getActionGroup() {
    long cPtr = ArNetworkingJavaJNI.ArServerModeIdle_getActionGroup(swigCPtr, this);
    return (cPtr == 0) ? null : new ArActionGroup(cPtr, false);
  }

  public void addToConfig(ArConfig config, String section) {
    ArNetworkingJavaJNI.ArServerModeIdle_addToConfig__SWIG_0(swigCPtr, this, ArConfig.getCPtr(config), config, section);
  }

  public void addToConfig(ArConfig config) {
    ArNetworkingJavaJNI.ArServerModeIdle_addToConfig__SWIG_1(swigCPtr, this, ArConfig.getCPtr(config), config);
  }

  public void setUseLocationDependentDevices(boolean useLocationDependentDevices, boolean internal) {
    ArNetworkingJavaJNI.ArServerModeIdle_setUseLocationDependentDevices__SWIG_0(swigCPtr, this, useLocationDependentDevices, internal);
  }

  public void setUseLocationDependentDevices(boolean useLocationDependentDevices) {
    ArNetworkingJavaJNI.ArServerModeIdle_setUseLocationDependentDevices__SWIG_1(swigCPtr, this, useLocationDependentDevices);
  }

  public boolean getUseLocationDependentDevices() {
    return ArNetworkingJavaJNI.ArServerModeIdle_getUseLocationDependentDevices(swigCPtr, this);
  }

}
