/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.ArNetworking;
import com.mobilerobots.Aria.*;
public class ArServerSimpleLogRobotDebugPackets {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  /* for internal use by swig only */
  public ArServerSimpleLogRobotDebugPackets(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArServerSimpleLogRobotDebugPackets obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ArNetworkingJavaJNI.delete_ArServerSimpleLogRobotDebugPackets(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ArServerSimpleLogRobotDebugPackets(ArServerHandlerCommands commands, ArRobot robot, String baseDirectory) {
    this(ArNetworkingJavaJNI.new_ArServerSimpleLogRobotDebugPackets__SWIG_0(ArServerHandlerCommands.getCPtr(commands), commands, ArRobot.getCPtr(robot), robot, baseDirectory), true);
  }

  public ArServerSimpleLogRobotDebugPackets(ArServerHandlerCommands commands, ArRobot robot) {
    this(ArNetworkingJavaJNI.new_ArServerSimpleLogRobotDebugPackets__SWIG_1(ArServerHandlerCommands.getCPtr(commands), commands, ArRobot.getCPtr(robot), robot), true);
  }

  public boolean startLogging(String fileName) {
    return ArNetworkingJavaJNI.ArServerSimpleLogRobotDebugPackets_startLogging__SWIG_0(swigCPtr, this, fileName);
  }

  public boolean startLogging() {
    return ArNetworkingJavaJNI.ArServerSimpleLogRobotDebugPackets_startLogging__SWIG_1(swigCPtr, this);
  }

  public boolean stopLogging() {
    return ArNetworkingJavaJNI.ArServerSimpleLogRobotDebugPackets_stopLogging(swigCPtr, this);
  }

  public boolean packetHandler(ArRobotPacket packet) {
    return ArNetworkingJavaJNI.ArServerSimpleLogRobotDebugPackets_packetHandler(swigCPtr, this, ArRobotPacket.getCPtr(packet), packet);
  }

  public void addToInfoGroup(ArStringInfoGroup infoGroup, String name, int whichVal, String format) {
    ArNetworkingJavaJNI.ArServerSimpleLogRobotDebugPackets_addToInfoGroup__SWIG_0(swigCPtr, this, ArStringInfoGroup.getCPtr(infoGroup), infoGroup, name, whichVal, format);
  }

  public void addToInfoGroup(ArStringInfoGroup infoGroup, String name, int whichVal) {
    ArNetworkingJavaJNI.ArServerSimpleLogRobotDebugPackets_addToInfoGroup__SWIG_1(swigCPtr, this, ArStringInfoGroup.getCPtr(infoGroup), infoGroup, name, whichVal);
  }

  public int getNumValues() {
    return ArNetworkingJavaJNI.ArServerSimpleLogRobotDebugPackets_getNumValues(swigCPtr, this);
  }

  public int getValue(int whichVal) {
    return ArNetworkingJavaJNI.ArServerSimpleLogRobotDebugPackets_getValue(swigCPtr, this, whichVal);
  }

}
