/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.ArNetworking;
import com.mobilerobots.Aria.*;
public class ArServerInfoStrings {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  /* for internal use by swig only */
  public ArServerInfoStrings(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArServerInfoStrings obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ArNetworkingJavaJNI.delete_ArServerInfoStrings(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ArServerInfoStrings(ArServerBase server) {
    this(ArNetworkingJavaJNI.new_ArServerInfoStrings(ArServerBase.getCPtr(server), server), true);
  }

  public void netGetStringsInfo(ArServerClient client, ArNetPacket packet) {
    ArNetworkingJavaJNI.ArServerInfoStrings_netGetStringsInfo(swigCPtr, this, ArServerClient.getCPtr(client), client, ArNetPacket.getCPtr(packet), packet);
  }

  public void netGetStrings(ArServerClient client, ArNetPacket packet) {
    ArNetworkingJavaJNI.ArServerInfoStrings_netGetStrings(swigCPtr, this, ArServerClient.getCPtr(client), client, ArNetPacket.getCPtr(packet), packet);
  }

  public void addString(String name, int maxLen, SWIGTYPE_p_ArFunctor2T_char_p_unsigned_short_t functor) {
    ArNetworkingJavaJNI.ArServerInfoStrings_addString(swigCPtr, this, name, maxLen, SWIGTYPE_p_ArFunctor2T_char_p_unsigned_short_t.getCPtr(functor));
  }

  public SWIGTYPE_p_ArFunctor3T_char_const_p_unsigned_short_ArFunctor2T_char_p_unsigned_short_t_p_t getAddStringFunctor() {
    long cPtr = ArNetworkingJavaJNI.ArServerInfoStrings_getAddStringFunctor(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_ArFunctor3T_char_const_p_unsigned_short_ArFunctor2T_char_p_unsigned_short_t_p_t(cPtr, false);
  }

}
