/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.ArNetworking;
import com.mobilerobots.Aria.*;
public class ArServerClientData {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  /* for internal use by swig only */
  public ArServerClientData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArServerClientData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        ArNetworkingJavaJNI.delete_ArServerClientData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ArServerClientData(ArServerData serverData, int mSecInterval, ArNetPacket packet) {
    this(ArNetworkingJavaJNI.new_ArServerClientData(ArServerData.getCPtr(serverData), serverData, mSecInterval, ArNetPacket.getCPtr(packet), packet), true);
  }

  public ArServerData getServerData() {
    long cPtr = ArNetworkingJavaJNI.ArServerClientData_getServerData(swigCPtr, this);
    return (cPtr == 0) ? null : new ArServerData(cPtr, false);
  }

  public int getMSec() {
    return ArNetworkingJavaJNI.ArServerClientData_getMSec(swigCPtr, this);
  }

  public ArNetPacket getPacket() {
    long cPtr = ArNetworkingJavaJNI.ArServerClientData_getPacket(swigCPtr, this);
    return (cPtr == 0) ? null : new ArNetPacket(cPtr, false);
  }

  public ArTime getLastSent() {
    return new ArTime(ArNetworkingJavaJNI.ArServerClientData_getLastSent(swigCPtr, this), true);
  }

  public void setLastSentToNow() {
    ArNetworkingJavaJNI.ArServerClientData_setLastSentToNow(swigCPtr, this);
  }

  public void setMSec(int mSec) {
    ArNetworkingJavaJNI.ArServerClientData_setMSec(swigCPtr, this, mSec);
  }

  public void setPacket(ArNetPacket packet) {
    ArNetworkingJavaJNI.ArServerClientData_setPacket(swigCPtr, this, ArNetPacket.getCPtr(packet), packet);
  }

}
