/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.ArNetworking;

public class SWIGTYPE_p_in_addr {
  private long swigCPtr;

  /* for internal use by swig only */
  public SWIGTYPE_p_in_addr(long cPtr, boolean bFutureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_in_addr() {
    swigCPtr = 0;
  }

  /* for internal use by swig only */
  public static long getCPtr(SWIGTYPE_p_in_addr obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }
}

