/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArActionLimiterForwards extends ArAction {
  /* (begin code from javabody_derived typemap) */

  private long swigCPtr;

  /* for internal use by swig only */
  public ArActionLimiterForwards(long cPtr, boolean cMemoryOwn) {
    super(AriaJavaJNI.SWIGArActionLimiterForwardsUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArActionLimiterForwards obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody_derived typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArActionLimiterForwards(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ArActionLimiterForwards(String name, double stopDistance, double slowDistance, double slowSpeed, double widthRatio) {
    this(AriaJavaJNI.new_ArActionLimiterForwards__SWIG_0(name, stopDistance, slowDistance, slowSpeed, widthRatio), true);
  }

  public ArActionLimiterForwards(String name, double stopDistance, double slowDistance, double slowSpeed) {
    this(AriaJavaJNI.new_ArActionLimiterForwards__SWIG_1(name, stopDistance, slowDistance, slowSpeed), true);
  }

  public ArActionLimiterForwards(String name, double stopDistance, double slowDistance) {
    this(AriaJavaJNI.new_ArActionLimiterForwards__SWIG_2(name, stopDistance, slowDistance), true);
  }

  public ArActionLimiterForwards(String name, double stopDistance) {
    this(AriaJavaJNI.new_ArActionLimiterForwards__SWIG_3(name, stopDistance), true);
  }

  public ArActionLimiterForwards(String name) {
    this(AriaJavaJNI.new_ArActionLimiterForwards__SWIG_4(name), true);
  }

  public ArActionLimiterForwards() {
    this(AriaJavaJNI.new_ArActionLimiterForwards__SWIG_5(), true);
  }

  public ArActionDesired fire(ArActionDesired currentDesired) {
    long cPtr = AriaJavaJNI.ArActionLimiterForwards_fire(swigCPtr, this, ArActionDesired.getCPtr(currentDesired), currentDesired);
    return (cPtr == 0) ? null : new ArActionDesired(cPtr, false);
  }

  public ArActionDesired getDesired() {
    long cPtr = AriaJavaJNI.ArActionLimiterForwards_getDesired(swigCPtr, this);
    return (cPtr == 0) ? null : new ArActionDesired(cPtr, false);
  }

  public void setParameters(double stopDistance, double slowDistance, double slowSpeed, double widthRatio) {
    AriaJavaJNI.ArActionLimiterForwards_setParameters__SWIG_0(swigCPtr, this, stopDistance, slowDistance, slowSpeed, widthRatio);
  }

  public void setParameters(double stopDistance, double slowDistance, double slowSpeed) {
    AriaJavaJNI.ArActionLimiterForwards_setParameters__SWIG_1(swigCPtr, this, stopDistance, slowDistance, slowSpeed);
  }

  public void setParameters(double stopDistance, double slowDistance) {
    AriaJavaJNI.ArActionLimiterForwards_setParameters__SWIG_2(swigCPtr, this, stopDistance, slowDistance);
  }

  public void setParameters(double stopDistance) {
    AriaJavaJNI.ArActionLimiterForwards_setParameters__SWIG_3(swigCPtr, this, stopDistance);
  }

  public void setParameters() {
    AriaJavaJNI.ArActionLimiterForwards_setParameters__SWIG_4(swigCPtr, this);
  }

}
