/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArActionIRs extends ArAction {
  /* (begin code from javabody_derived typemap) */

  private long swigCPtr;

  /* for internal use by swig only */
  public ArActionIRs(long cPtr, boolean cMemoryOwn) {
    super(AriaJavaJNI.SWIGArActionIRsUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArActionIRs obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody_derived typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArActionIRs(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ArActionIRs(String name, double backOffSpeed, int backOffTime, int turnTime, boolean setMaximums) {
    this(AriaJavaJNI.new_ArActionIRs__SWIG_0(name, backOffSpeed, backOffTime, turnTime, setMaximums), true);
  }

  public ArActionIRs(String name, double backOffSpeed, int backOffTime, int turnTime) {
    this(AriaJavaJNI.new_ArActionIRs__SWIG_1(name, backOffSpeed, backOffTime, turnTime), true);
  }

  public ArActionIRs(String name, double backOffSpeed, int backOffTime) {
    this(AriaJavaJNI.new_ArActionIRs__SWIG_2(name, backOffSpeed, backOffTime), true);
  }

  public ArActionIRs(String name, double backOffSpeed) {
    this(AriaJavaJNI.new_ArActionIRs__SWIG_3(name, backOffSpeed), true);
  }

  public ArActionIRs(String name) {
    this(AriaJavaJNI.new_ArActionIRs__SWIG_4(name), true);
  }

  public ArActionIRs() {
    this(AriaJavaJNI.new_ArActionIRs__SWIG_5(), true);
  }

  public ArActionDesired fire(ArActionDesired currentDesired) {
    long cPtr = AriaJavaJNI.ArActionIRs_fire(swigCPtr, this, ArActionDesired.getCPtr(currentDesired), currentDesired);
    return (cPtr == 0) ? null : new ArActionDesired(cPtr, false);
  }

  public void setRobot(ArRobot robot) {
    AriaJavaJNI.ArActionIRs_setRobot(swigCPtr, this, ArRobot.getCPtr(robot), robot);
  }

  public ArActionDesired getDesired() {
    long cPtr = AriaJavaJNI.ArActionIRs_getDesired(swigCPtr, this);
    return (cPtr == 0) ? null : new ArActionDesired(cPtr, false);
  }

}
