/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArActionLimiterBackwards extends ArAction {
  /* (begin code from javabody_derived typemap) */

  private long swigCPtr;

  /* for internal use by swig only */
  public ArActionLimiterBackwards(long cPtr, boolean cMemoryOwn) {
    super(AriaJavaJNI.SWIGArActionLimiterBackwardsUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArActionLimiterBackwards obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody_derived typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArActionLimiterBackwards(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ArActionLimiterBackwards(String name, double stopDistance, double slowDistance, double maxBackwardsSpeed, double widthRatio, boolean avoidLocationDependentObstacles) {
    this(AriaJavaJNI.new_ArActionLimiterBackwards__SWIG_0(name, stopDistance, slowDistance, maxBackwardsSpeed, widthRatio, avoidLocationDependentObstacles), true);
  }

  public ArActionLimiterBackwards(String name, double stopDistance, double slowDistance, double maxBackwardsSpeed, double widthRatio) {
    this(AriaJavaJNI.new_ArActionLimiterBackwards__SWIG_1(name, stopDistance, slowDistance, maxBackwardsSpeed, widthRatio), true);
  }

  public ArActionLimiterBackwards(String name, double stopDistance, double slowDistance, double maxBackwardsSpeed) {
    this(AriaJavaJNI.new_ArActionLimiterBackwards__SWIG_2(name, stopDistance, slowDistance, maxBackwardsSpeed), true);
  }

  public ArActionLimiterBackwards(String name, double stopDistance, double slowDistance) {
    this(AriaJavaJNI.new_ArActionLimiterBackwards__SWIG_3(name, stopDistance, slowDistance), true);
  }

  public ArActionLimiterBackwards(String name, double stopDistance) {
    this(AriaJavaJNI.new_ArActionLimiterBackwards__SWIG_4(name, stopDistance), true);
  }

  public ArActionLimiterBackwards(String name) {
    this(AriaJavaJNI.new_ArActionLimiterBackwards__SWIG_5(name), true);
  }

  public ArActionLimiterBackwards() {
    this(AriaJavaJNI.new_ArActionLimiterBackwards__SWIG_6(), true);
  }

  public ArActionDesired fire(ArActionDesired currentDesired) {
    long cPtr = AriaJavaJNI.ArActionLimiterBackwards_fire(swigCPtr, this, ArActionDesired.getCPtr(currentDesired), currentDesired);
    return (cPtr == 0) ? null : new ArActionDesired(cPtr, false);
  }

  public ArActionDesired getDesired() {
    long cPtr = AriaJavaJNI.ArActionLimiterBackwards_getDesired(swigCPtr, this);
    return (cPtr == 0) ? null : new ArActionDesired(cPtr, false);
  }

}
