/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArActionAvoidSide extends ArAction {
  /* (begin code from javabody_derived typemap) */

  private long swigCPtr;

  /* for internal use by swig only */
  public ArActionAvoidSide(long cPtr, boolean cMemoryOwn) {
    super(AriaJavaJNI.SWIGArActionAvoidSideUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArActionAvoidSide obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody_derived typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArActionAvoidSide(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ArActionAvoidSide(String name, double obstacleDistance, double turnAmount) {
    this(AriaJavaJNI.new_ArActionAvoidSide__SWIG_0(name, obstacleDistance, turnAmount), true);
  }

  public ArActionAvoidSide(String name, double obstacleDistance) {
    this(AriaJavaJNI.new_ArActionAvoidSide__SWIG_1(name, obstacleDistance), true);
  }

  public ArActionAvoidSide(String name) {
    this(AriaJavaJNI.new_ArActionAvoidSide__SWIG_2(name), true);
  }

  public ArActionAvoidSide() {
    this(AriaJavaJNI.new_ArActionAvoidSide__SWIG_3(), true);
  }

  public ArActionDesired fire(ArActionDesired currentDesired) {
    long cPtr = AriaJavaJNI.ArActionAvoidSide_fire(swigCPtr, this, ArActionDesired.getCPtr(currentDesired), currentDesired);
    return (cPtr == 0) ? null : new ArActionDesired(cPtr, false);
  }

  public ArActionDesired getDesired() {
    long cPtr = AriaJavaJNI.ArActionAvoidSide_getDesired(swigCPtr, this);
    return (cPtr == 0) ? null : new ArActionDesired(cPtr, false);
  }

}
