/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArActionMovementParameters extends ArAction {
  /* (begin code from javabody_derived typemap) */

  private long swigCPtr;

  /* for internal use by swig only */
  public ArActionMovementParameters(long cPtr, boolean cMemoryOwn) {
    super(AriaJavaJNI.SWIGArActionMovementParametersUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArActionMovementParameters obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody_derived typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArActionMovementParameters(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ArActionMovementParameters(String name, boolean overrideFaster, boolean addLatVelIfAvailable) {
    this(AriaJavaJNI.new_ArActionMovementParameters__SWIG_0(name, overrideFaster, addLatVelIfAvailable), true);
  }

  public ArActionMovementParameters(String name, boolean overrideFaster) {
    this(AriaJavaJNI.new_ArActionMovementParameters__SWIG_1(name, overrideFaster), true);
  }

  public ArActionMovementParameters(String name) {
    this(AriaJavaJNI.new_ArActionMovementParameters__SWIG_2(name), true);
  }

  public ArActionMovementParameters() {
    this(AriaJavaJNI.new_ArActionMovementParameters__SWIG_3(), true);
  }

  public ArActionDesired fire(ArActionDesired currentDesired) {
    long cPtr = AriaJavaJNI.ArActionMovementParameters_fire(swigCPtr, this, ArActionDesired.getCPtr(currentDesired), currentDesired);
    return (cPtr == 0) ? null : new ArActionDesired(cPtr, false);
  }

  public ArActionDesired getDesired() {
    long cPtr = AriaJavaJNI.ArActionMovementParameters_getDesired(swigCPtr, this);
    return (cPtr == 0) ? null : new ArActionDesired(cPtr, false);
  }

  public void enable() {
    AriaJavaJNI.ArActionMovementParameters_enable(swigCPtr, this);
  }

  public void enableOnceFromSector(ArMapObject mapObject) {
    AriaJavaJNI.ArActionMovementParameters_enableOnceFromSector(swigCPtr, this, ArMapObject.getCPtr(mapObject), mapObject);
  }

  public void disable() {
    AriaJavaJNI.ArActionMovementParameters_disable(swigCPtr, this);
  }

  public void setParameters(double maxVel, double maxNegVel, double transAccel, double transDecel, double rotVelMax, double rotAccel, double rotDecel, double latVelMax, double latAccel, double latDecel) {
    AriaJavaJNI.ArActionMovementParameters_setParameters__SWIG_0(swigCPtr, this, maxVel, maxNegVel, transAccel, transDecel, rotVelMax, rotAccel, rotDecel, latVelMax, latAccel, latDecel);
  }

  public void setParameters(double maxVel, double maxNegVel, double transAccel, double transDecel, double rotVelMax, double rotAccel, double rotDecel, double latVelMax, double latAccel) {
    AriaJavaJNI.ArActionMovementParameters_setParameters__SWIG_1(swigCPtr, this, maxVel, maxNegVel, transAccel, transDecel, rotVelMax, rotAccel, rotDecel, latVelMax, latAccel);
  }

  public void setParameters(double maxVel, double maxNegVel, double transAccel, double transDecel, double rotVelMax, double rotAccel, double rotDecel, double latVelMax) {
    AriaJavaJNI.ArActionMovementParameters_setParameters__SWIG_2(swigCPtr, this, maxVel, maxNegVel, transAccel, transDecel, rotVelMax, rotAccel, rotDecel, latVelMax);
  }

  public void setParameters(double maxVel, double maxNegVel, double transAccel, double transDecel, double rotVelMax, double rotAccel, double rotDecel) {
    AriaJavaJNI.ArActionMovementParameters_setParameters__SWIG_3(swigCPtr, this, maxVel, maxNegVel, transAccel, transDecel, rotVelMax, rotAccel, rotDecel);
  }

  public void setParameters(double maxVel, double maxNegVel, double transAccel, double transDecel, double rotVelMax, double rotAccel) {
    AriaJavaJNI.ArActionMovementParameters_setParameters__SWIG_4(swigCPtr, this, maxVel, maxNegVel, transAccel, transDecel, rotVelMax, rotAccel);
  }

  public void setParameters(double maxVel, double maxNegVel, double transAccel, double transDecel, double rotVelMax) {
    AriaJavaJNI.ArActionMovementParameters_setParameters__SWIG_5(swigCPtr, this, maxVel, maxNegVel, transAccel, transDecel, rotVelMax);
  }

  public void setParameters(double maxVel, double maxNegVel, double transAccel, double transDecel) {
    AriaJavaJNI.ArActionMovementParameters_setParameters__SWIG_6(swigCPtr, this, maxVel, maxNegVel, transAccel, transDecel);
  }

  public void setParameters(double maxVel, double maxNegVel, double transAccel) {
    AriaJavaJNI.ArActionMovementParameters_setParameters__SWIG_7(swigCPtr, this, maxVel, maxNegVel, transAccel);
  }

  public void setParameters(double maxVel, double maxNegVel) {
    AriaJavaJNI.ArActionMovementParameters_setParameters__SWIG_8(swigCPtr, this, maxVel, maxNegVel);
  }

  public void setParameters(double maxVel) {
    AriaJavaJNI.ArActionMovementParameters_setParameters__SWIG_9(swigCPtr, this, maxVel);
  }

  public void setParameters() {
    AriaJavaJNI.ArActionMovementParameters_setParameters__SWIG_10(swigCPtr, this);
  }

  public void addToConfig(ArConfig config, String section, String prefix) {
    AriaJavaJNI.ArActionMovementParameters_addToConfig__SWIG_0(swigCPtr, this, ArConfig.getCPtr(config), config, section, prefix);
  }

  public void addToConfig(ArConfig config, String section) {
    AriaJavaJNI.ArActionMovementParameters_addToConfig__SWIG_1(swigCPtr, this, ArConfig.getCPtr(config), config, section);
  }

}
