/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArActionRobotJoydrive extends ArAction {
  /* (begin code from javabody_derived typemap) */

  private long swigCPtr;

  /* for internal use by swig only */
  public ArActionRobotJoydrive(long cPtr, boolean cMemoryOwn) {
    super(AriaJavaJNI.SWIGArActionRobotJoydriveUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArActionRobotJoydrive obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody_derived typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArActionRobotJoydrive(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ArActionRobotJoydrive(String name, boolean requireDeadmanPushed) {
    this(AriaJavaJNI.new_ArActionRobotJoydrive__SWIG_0(name, requireDeadmanPushed), true);
  }

  public ArActionRobotJoydrive(String name) {
    this(AriaJavaJNI.new_ArActionRobotJoydrive__SWIG_1(name), true);
  }

  public ArActionRobotJoydrive() {
    this(AriaJavaJNI.new_ArActionRobotJoydrive__SWIG_2(), true);
  }

  public ArActionDesired fire(ArActionDesired currentDesired) {
    long cPtr = AriaJavaJNI.ArActionRobotJoydrive_fire(swigCPtr, this, ArActionDesired.getCPtr(currentDesired), currentDesired);
    return (cPtr == 0) ? null : new ArActionDesired(cPtr, false);
  }

  public ArActionDesired getDesired() {
    long cPtr = AriaJavaJNI.ArActionRobotJoydrive_getDesired(swigCPtr, this);
    return (cPtr == 0) ? null : new ArActionDesired(cPtr, false);
  }

  public void setRobot(ArRobot robot) {
    AriaJavaJNI.ArActionRobotJoydrive_setRobot(swigCPtr, this, ArRobot.getCPtr(robot), robot);
  }

}
