/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArActionAvoidFront extends ArAction {
  /* (begin code from javabody_derived typemap) */

  private long swigCPtr;

  /* for internal use by swig only */
  public ArActionAvoidFront(long cPtr, boolean cMemoryOwn) {
    super(AriaJavaJNI.SWIGArActionAvoidFrontUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArActionAvoidFront obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody_derived typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArActionAvoidFront(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ArActionAvoidFront(String name, double obstacleDistance, double avoidVelocity, double turnAmount, boolean useTableIRIfAvail) {
    this(AriaJavaJNI.new_ArActionAvoidFront__SWIG_0(name, obstacleDistance, avoidVelocity, turnAmount, useTableIRIfAvail), true);
  }

  public ArActionAvoidFront(String name, double obstacleDistance, double avoidVelocity, double turnAmount) {
    this(AriaJavaJNI.new_ArActionAvoidFront__SWIG_1(name, obstacleDistance, avoidVelocity, turnAmount), true);
  }

  public ArActionAvoidFront(String name, double obstacleDistance, double avoidVelocity) {
    this(AriaJavaJNI.new_ArActionAvoidFront__SWIG_2(name, obstacleDistance, avoidVelocity), true);
  }

  public ArActionAvoidFront(String name, double obstacleDistance) {
    this(AriaJavaJNI.new_ArActionAvoidFront__SWIG_3(name, obstacleDistance), true);
  }

  public ArActionAvoidFront(String name) {
    this(AriaJavaJNI.new_ArActionAvoidFront__SWIG_4(name), true);
  }

  public ArActionAvoidFront() {
    this(AriaJavaJNI.new_ArActionAvoidFront__SWIG_5(), true);
  }

  public ArActionDesired fire(ArActionDesired currentDesired) {
    long cPtr = AriaJavaJNI.ArActionAvoidFront_fire(swigCPtr, this, ArActionDesired.getCPtr(currentDesired), currentDesired);
    return (cPtr == 0) ? null : new ArActionDesired(cPtr, false);
  }

  public ArActionDesired getDesired() {
    long cPtr = AriaJavaJNI.ArActionAvoidFront_getDesired(swigCPtr, this);
    return (cPtr == 0) ? null : new ArActionDesired(cPtr, false);
  }

}
