/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArActionInput extends ArAction {
  /* (begin code from javabody_derived typemap) */

  private long swigCPtr;

  /* for internal use by swig only */
  public ArActionInput(long cPtr, boolean cMemoryOwn) {
    super(AriaJavaJNI.SWIGArActionInputUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArActionInput obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody_derived typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArActionInput(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ArActionInput(String name) {
    this(AriaJavaJNI.new_ArActionInput__SWIG_0(name), true);
  }

  public ArActionInput() {
    this(AriaJavaJNI.new_ArActionInput__SWIG_1(), true);
  }

  public void setVel(double vel) {
    AriaJavaJNI.ArActionInput_setVel(swigCPtr, this, vel);
  }

  public void deltaHeadingFromCurrent(double delta) {
    AriaJavaJNI.ArActionInput_deltaHeadingFromCurrent(swigCPtr, this, delta);
  }

  public void setRotVel(double rotVel) {
    AriaJavaJNI.ArActionInput_setRotVel(swigCPtr, this, rotVel);
  }

  public void setHeading(double heading) {
    AriaJavaJNI.ArActionInput_setHeading(swigCPtr, this, heading);
  }

  public void clear() {
    AriaJavaJNI.ArActionInput_clear(swigCPtr, this);
  }

  public ArActionDesired fire(ArActionDesired currentDesired) {
    long cPtr = AriaJavaJNI.ArActionInput_fire(swigCPtr, this, ArActionDesired.getCPtr(currentDesired), currentDesired);
    return (cPtr == 0) ? null : new ArActionDesired(cPtr, false);
  }

  public ArActionDesired getDesired() {
    long cPtr = AriaJavaJNI.ArActionInput_getDesired(swigCPtr, this);
    return (cPtr == 0) ? null : new ArActionDesired(cPtr, false);
  }

}
