/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArActionGroup {
  /* (begin code from javabody typemap) */

  private long swigCPtr;
  protected boolean swigCMemOwn;

  /* for internal use by swig only */
  public ArActionGroup(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArActionGroup obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArActionGroup(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ArActionGroup(ArRobot robot) {
    this(AriaJavaJNI.new_ArActionGroup(ArRobot.getCPtr(robot), robot), true);
  }

  public void addAction(ArAction action, int priority) {
    AriaJavaJNI.ArActionGroup_addAction(swigCPtr, this, ArAction.getCPtr(action), action, priority);
  }

  public void remAction(ArAction action) {
    AriaJavaJNI.ArActionGroup_remAction(swigCPtr, this, ArAction.getCPtr(action), action);
  }

  public void activate() {
    AriaJavaJNI.ArActionGroup_activate(swigCPtr, this);
  }

  public void activateExclusive() {
    AriaJavaJNI.ArActionGroup_activateExclusive(swigCPtr, this);
  }

  public void deactivate() {
    AriaJavaJNI.ArActionGroup_deactivate(swigCPtr, this);
  }

  public void removeActions() {
    AriaJavaJNI.ArActionGroup_removeActions(swigCPtr, this);
  }

  public void deleteActions() {
    AriaJavaJNI.ArActionGroup_deleteActions(swigCPtr, this);
  }

  public SWIGTYPE_p_std__listT_ArAction_p_t getActionList() {
    long cPtr = AriaJavaJNI.ArActionGroup_getActionList(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_std__listT_ArAction_p_t(cPtr, false);
  }

}
