/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArActionGroupInput extends ArActionGroup {
  /* (begin code from javabody_derived typemap) */

  private long swigCPtr;

  /* for internal use by swig only */
  public ArActionGroupInput(long cPtr, boolean cMemoryOwn) {
    super(AriaJavaJNI.SWIGArActionGroupInputUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArActionGroupInput obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody_derived typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArActionGroupInput(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ArActionGroupInput(ArRobot robot) {
    this(AriaJavaJNI.new_ArActionGroupInput(ArRobot.getCPtr(robot), robot), true);
  }

  public void setVel(double vel) {
    AriaJavaJNI.ArActionGroupInput_setVel(swigCPtr, this, vel);
  }

  public void setRotVel(double rotVel) {
    AriaJavaJNI.ArActionGroupInput_setRotVel(swigCPtr, this, rotVel);
  }

  public void setHeading(double heading) {
    AriaJavaJNI.ArActionGroupInput_setHeading(swigCPtr, this, heading);
  }

  public void deltaHeadingFromCurrent(double delta) {
    AriaJavaJNI.ArActionGroupInput_deltaHeadingFromCurrent(swigCPtr, this, delta);
  }

  public void clear() {
    AriaJavaJNI.ArActionGroupInput_clear(swigCPtr, this);
  }

  public ArActionInput getActionInput() {
    long cPtr = AriaJavaJNI.ArActionGroupInput_getActionInput(swigCPtr, this);
    return (cPtr == 0) ? null : new ArActionInput(cPtr, false);
  }

}
