/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArActionGroupRatioDriveUnsafe extends ArActionGroup {
  /* (begin code from javabody_derived typemap) */

  private long swigCPtr;

  /* for internal use by swig only */
  public ArActionGroupRatioDriveUnsafe(long cPtr, boolean cMemoryOwn) {
    super(AriaJavaJNI.SWIGArActionGroupRatioDriveUnsafeUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArActionGroupRatioDriveUnsafe obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody_derived typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArActionGroupRatioDriveUnsafe(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ArActionGroupRatioDriveUnsafe(ArRobot robot) {
    this(AriaJavaJNI.new_ArActionGroupRatioDriveUnsafe(ArRobot.getCPtr(robot), robot), true);
  }

  public ArActionRatioInput getActionRatioInput() {
    long cPtr = AriaJavaJNI.ArActionGroupRatioDriveUnsafe_getActionRatioInput(swigCPtr, this);
    return (cPtr == 0) ? null : new ArActionRatioInput(cPtr, false);
  }

  public void addToConfig(ArConfig config, String section) {
    AriaJavaJNI.ArActionGroupRatioDriveUnsafe_addToConfig(swigCPtr, this, ArConfig.getCPtr(config), config, section);
  }

}
