/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArActionStallRecover extends ArAction {
  /* (begin code from javabody_derived typemap) */

  private long swigCPtr;

  /* for internal use by swig only */
  public ArActionStallRecover(long cPtr, boolean cMemoryOwn) {
    super(AriaJavaJNI.SWIGArActionStallRecoverUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArActionStallRecover obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody_derived typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArActionStallRecover(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ArActionStallRecover(String name, double obstacleDistance, int cyclesToMove, double speed, double degreesToTurn) {
    this(AriaJavaJNI.new_ArActionStallRecover__SWIG_0(name, obstacleDistance, cyclesToMove, speed, degreesToTurn), true);
  }

  public ArActionStallRecover(String name, double obstacleDistance, int cyclesToMove, double speed) {
    this(AriaJavaJNI.new_ArActionStallRecover__SWIG_1(name, obstacleDistance, cyclesToMove, speed), true);
  }

  public ArActionStallRecover(String name, double obstacleDistance, int cyclesToMove) {
    this(AriaJavaJNI.new_ArActionStallRecover__SWIG_2(name, obstacleDistance, cyclesToMove), true);
  }

  public ArActionStallRecover(String name, double obstacleDistance) {
    this(AriaJavaJNI.new_ArActionStallRecover__SWIG_3(name, obstacleDistance), true);
  }

  public ArActionStallRecover(String name) {
    this(AriaJavaJNI.new_ArActionStallRecover__SWIG_4(name), true);
  }

  public ArActionStallRecover() {
    this(AriaJavaJNI.new_ArActionStallRecover__SWIG_5(), true);
  }

  public ArActionDesired fire(ArActionDesired currentDesired) {
    long cPtr = AriaJavaJNI.ArActionStallRecover_fire(swigCPtr, this, ArActionDesired.getCPtr(currentDesired), currentDesired);
    return (cPtr == 0) ? null : new ArActionDesired(cPtr, false);
  }

  public ArActionDesired getDesired() {
    long cPtr = AriaJavaJNI.ArActionStallRecover_getDesired(swigCPtr, this);
    return (cPtr == 0) ? null : new ArActionDesired(cPtr, false);
  }

  public void addToConfig(ArConfig config, String sectionName, int priority) {
    AriaJavaJNI.ArActionStallRecover_addToConfig__SWIG_0(swigCPtr, this, ArConfig.getCPtr(config), config, sectionName, priority);
  }

  public void addToConfig(ArConfig config, String sectionName) {
    AriaJavaJNI.ArActionStallRecover_addToConfig__SWIG_1(swigCPtr, this, ArConfig.getCPtr(config), config, sectionName);
  }

}
