/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArActionTurn extends ArAction {
  /* (begin code from javabody_derived typemap) */

  private long swigCPtr;

  /* for internal use by swig only */
  public ArActionTurn(long cPtr, boolean cMemoryOwn) {
    super(AriaJavaJNI.SWIGArActionTurnUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArActionTurn obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody_derived typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArActionTurn(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ArActionTurn(String name, double speedStartTurn, double speedFullTurn, double turnAmount) {
    this(AriaJavaJNI.new_ArActionTurn__SWIG_0(name, speedStartTurn, speedFullTurn, turnAmount), true);
  }

  public ArActionTurn(String name, double speedStartTurn, double speedFullTurn) {
    this(AriaJavaJNI.new_ArActionTurn__SWIG_1(name, speedStartTurn, speedFullTurn), true);
  }

  public ArActionTurn(String name, double speedStartTurn) {
    this(AriaJavaJNI.new_ArActionTurn__SWIG_2(name, speedStartTurn), true);
  }

  public ArActionTurn(String name) {
    this(AriaJavaJNI.new_ArActionTurn__SWIG_3(name), true);
  }

  public ArActionTurn() {
    this(AriaJavaJNI.new_ArActionTurn__SWIG_4(), true);
  }

  public ArActionDesired fire(ArActionDesired currentDesired) {
    long cPtr = AriaJavaJNI.ArActionTurn_fire(swigCPtr, this, ArActionDesired.getCPtr(currentDesired), currentDesired);
    return (cPtr == 0) ? null : new ArActionDesired(cPtr, false);
  }

  public ArActionDesired getDesired() {
    long cPtr = AriaJavaJNI.ArActionTurn_getDesired(swigCPtr, this);
    return (cPtr == 0) ? null : new ArActionDesired(cPtr, false);
  }

}
