/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArActionBumpers extends ArAction {
  /* (begin code from javabody_derived typemap) */

  private long swigCPtr;

  /* for internal use by swig only */
  public ArActionBumpers(long cPtr, boolean cMemoryOwn) {
    super(AriaJavaJNI.SWIGArActionBumpersUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArActionBumpers obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody_derived typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArActionBumpers(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ArActionBumpers(String name, double backOffSpeed, int backOffTime, int turnTime, boolean setMaximums) {
    this(AriaJavaJNI.new_ArActionBumpers__SWIG_0(name, backOffSpeed, backOffTime, turnTime, setMaximums), true);
  }

  public ArActionBumpers(String name, double backOffSpeed, int backOffTime, int turnTime) {
    this(AriaJavaJNI.new_ArActionBumpers__SWIG_1(name, backOffSpeed, backOffTime, turnTime), true);
  }

  public ArActionBumpers(String name, double backOffSpeed, int backOffTime) {
    this(AriaJavaJNI.new_ArActionBumpers__SWIG_2(name, backOffSpeed, backOffTime), true);
  }

  public ArActionBumpers(String name, double backOffSpeed) {
    this(AriaJavaJNI.new_ArActionBumpers__SWIG_3(name, backOffSpeed), true);
  }

  public ArActionBumpers(String name) {
    this(AriaJavaJNI.new_ArActionBumpers__SWIG_4(name), true);
  }

  public ArActionBumpers() {
    this(AriaJavaJNI.new_ArActionBumpers__SWIG_5(), true);
  }

  public ArActionDesired fire(ArActionDesired currentDesired) {
    long cPtr = AriaJavaJNI.ArActionBumpers_fire(swigCPtr, this, ArActionDesired.getCPtr(currentDesired), currentDesired);
    return (cPtr == 0) ? null : new ArActionDesired(cPtr, false);
  }

  public ArActionDesired getDesired() {
    long cPtr = AriaJavaJNI.ArActionBumpers_getDesired(swigCPtr, this);
    return (cPtr == 0) ? null : new ArActionDesired(cPtr, false);
  }

  public double findDegreesToTurn(int bumpValue, int whichBumper) {
    return AriaJavaJNI.ArActionBumpers_findDegreesToTurn(swigCPtr, this, bumpValue, whichBumper);
  }

}
