/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArAMPTUPacket extends ArBasePacket {
  /* (begin code from javabody_derived typemap) */

  private long swigCPtr;

  /* for internal use by swig only */
  public ArAMPTUPacket(long cPtr, boolean cMemoryOwn) {
    super(AriaJavaJNI.SWIGArAMPTUPacketUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArAMPTUPacket obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody_derived typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArAMPTUPacket(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ArAMPTUPacket(int bufferSize) {
    this(AriaJavaJNI.new_ArAMPTUPacket__SWIG_0(bufferSize), true);
  }

  public ArAMPTUPacket() {
    this(AriaJavaJNI.new_ArAMPTUPacket__SWIG_1(), true);
  }

  public short getUnitNumber() {
    return AriaJavaJNI.ArAMPTUPacket_getUnitNumber(swigCPtr, this);
  }

  public boolean setUnitNumber(short unitNumber) {
    return AriaJavaJNI.ArAMPTUPacket_setUnitNumber(swigCPtr, this, unitNumber);
  }

  public void byteToBuf(char val) {
    AriaJavaJNI.ArAMPTUPacket_byteToBuf(swigCPtr, this, val);
  }

  public void byte2ToBuf(short val) {
    AriaJavaJNI.ArAMPTUPacket_byte2ToBuf(swigCPtr, this, val);
  }

  public void finalizePacket() {
    AriaJavaJNI.ArAMPTUPacket_finalizePacket(swigCPtr, this);
  }

}
