/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArCameraCollectionItem {
  /* (begin code from javabody typemap) */

  private long swigCPtr;
  protected boolean swigCMemOwn;

  /* for internal use by swig only */
  public ArCameraCollectionItem(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArCameraCollectionItem obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArCameraCollectionItem(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String getCameraName() {
    return AriaJavaJNI.ArCameraCollectionItem_getCameraName(swigCPtr, this);
  }

  public void addToCameraCollection(ArCameraCollection collection) {
    AriaJavaJNI.ArCameraCollectionItem_addToCameraCollection(swigCPtr, this, ArCameraCollection.getCPtr(collection), collection);
  }

}
