/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArConfigArg_Double extends ArConfigArg {
  /* (begin code from javabody_derived typemap) */

  private long swigCPtr;

  /* for internal use by swig only */
  public ArConfigArg_Double(long cPtr, boolean cMemoryOwn) {
    super(AriaJavaJNI.SWIGArConfigArg_DoubleUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArConfigArg_Double obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody_derived typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArConfigArg_Double(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ArConfigArg_Double(String name, double d, String desc, double min, double max) {
    this(AriaJavaJNI.new_ArConfigArg_Double__SWIG_0(name, d, desc, min, max), true);
  }

  public ArConfigArg_Double(String name, double d, String desc, double min) {
    this(AriaJavaJNI.new_ArConfigArg_Double__SWIG_1(name, d, desc, min), true);
  }

  public ArConfigArg_Double(String name, double d, String desc) {
    this(AriaJavaJNI.new_ArConfigArg_Double__SWIG_2(name, d, desc), true);
  }

  public ArConfigArg_Double(String name, double d) {
    this(AriaJavaJNI.new_ArConfigArg_Double__SWIG_3(name, d), true);
  }

}
