/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArCompassConnector {
  /* (begin code from javabody typemap) */

  private long swigCPtr;
  protected boolean swigCMemOwn;

  /* for internal use by swig only */
  public ArCompassConnector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArCompassConnector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArCompassConnector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ArCompassConnector(ArArgumentParser argParser) {
    this(AriaJavaJNI.new_ArCompassConnector(ArArgumentParser.getCPtr(argParser), argParser), true);
  }

  public ArTCM2 create(ArRobot robot) {
    long cPtr = AriaJavaJNI.ArCompassConnector_create(swigCPtr, this, ArRobot.getCPtr(robot), robot);
    return (cPtr == 0) ? null : new ArTCM2(cPtr, false);
  }

  public boolean connect(ArTCM2 arg0) {
    return AriaJavaJNI.ArCompassConnector_connect(swigCPtr, this, ArTCM2.getCPtr(arg0), arg0);
  }

}
