/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArConfigArg_Int extends ArConfigArg {
  /* (begin code from javabody_derived typemap) */

  private long swigCPtr;

  /* for internal use by swig only */
  public ArConfigArg_Int(long cPtr, boolean cMemoryOwn) {
    super(AriaJavaJNI.SWIGArConfigArg_IntUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArConfigArg_Int obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody_derived typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArConfigArg_Int(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ArConfigArg_Int(String name, int i, String desc, int min, int max) {
    this(AriaJavaJNI.new_ArConfigArg_Int__SWIG_0(name, i, desc, min, max), true);
  }

  public ArConfigArg_Int(String name, int i, String desc, int min) {
    this(AriaJavaJNI.new_ArConfigArg_Int__SWIG_1(name, i, desc, min), true);
  }

  public ArConfigArg_Int(String name, int i, String desc) {
    this(AriaJavaJNI.new_ArConfigArg_Int__SWIG_2(name, i, desc), true);
  }

  public ArConfigArg_Int(String name, int i) {
    this(AriaJavaJNI.new_ArConfigArg_Int__SWIG_3(name, i), true);
  }

}
