/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArDPPTUPacket extends ArBasePacket {
  /* (begin code from javabody_derived typemap) */

  private long swigCPtr;

  /* for internal use by swig only */
  public ArDPPTUPacket(long cPtr, boolean cMemoryOwn) {
    super(AriaJavaJNI.SWIGArDPPTUPacketUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArDPPTUPacket obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody_derived typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArDPPTUPacket(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ArDPPTUPacket(int bufferSize) {
    this(AriaJavaJNI.new_ArDPPTUPacket__SWIG_0(bufferSize), true);
  }

  public ArDPPTUPacket() {
    this(AriaJavaJNI.new_ArDPPTUPacket__SWIG_1(), true);
  }

  public void byte2ToBuf(int val) {
    AriaJavaJNI.ArDPPTUPacket_byte2ToBuf(swigCPtr, this, val);
  }

  public void finalizePacket() {
    AriaJavaJNI.ArDPPTUPacket_finalizePacket(swigCPtr, this);
  }

}
