/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArDPPTUCommands {
  /* (begin code from javabody typemap) */

  private long swigCPtr;
  protected boolean swigCMemOwn;

  /* for internal use by swig only */
  public ArDPPTUCommands(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArDPPTUCommands obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArDPPTUCommands(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ArDPPTUCommands() {
    this(AriaJavaJNI.new_ArDPPTUCommands(), true);
  }

  public final static int DELIM = AriaJavaJNI.ArDPPTUCommands_DELIM_get();
  public final static int INIT = AriaJavaJNI.ArDPPTUCommands_INIT_get();
  public final static int ACCEL = AriaJavaJNI.ArDPPTUCommands_ACCEL_get();
  public final static int BASE = AriaJavaJNI.ArDPPTUCommands_BASE_get();
  public final static int CONTROL = AriaJavaJNI.ArDPPTUCommands_CONTROL_get();
  public final static int DISABLE = AriaJavaJNI.ArDPPTUCommands_DISABLE_get();
  public final static int ENABLE = AriaJavaJNI.ArDPPTUCommands_ENABLE_get();
  public final static int FACTORY = AriaJavaJNI.ArDPPTUCommands_FACTORY_get();
  public final static int HALT = AriaJavaJNI.ArDPPTUCommands_HALT_get();
  public final static int IMMED = AriaJavaJNI.ArDPPTUCommands_IMMED_get();
  public final static int LIMIT = AriaJavaJNI.ArDPPTUCommands_LIMIT_get();
  public final static int MONITOR = AriaJavaJNI.ArDPPTUCommands_MONITOR_get();
  public final static int OFFSET = AriaJavaJNI.ArDPPTUCommands_OFFSET_get();
  public final static int PAN = AriaJavaJNI.ArDPPTUCommands_PAN_get();
  public final static int RESET = AriaJavaJNI.ArDPPTUCommands_RESET_get();
  public final static int SPEED = AriaJavaJNI.ArDPPTUCommands_SPEED_get();
  public final static int TILT = AriaJavaJNI.ArDPPTUCommands_TILT_get();
  public final static int UPPER = AriaJavaJNI.ArDPPTUCommands_UPPER_get();
  public final static int VELOCITY = AriaJavaJNI.ArDPPTUCommands_VELOCITY_get();

}
