/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArDrawingData {
  /* (begin code from javabody typemap) */

  private long swigCPtr;
  protected boolean swigCMemOwn;

  /* for internal use by swig only */
  public ArDrawingData(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArDrawingData obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArDrawingData(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ArDrawingData(String shape, ArColor primaryColor, int size, int layer, long defaultRefreshTime, String visibility) {
    this(AriaJavaJNI.new_ArDrawingData__SWIG_0(shape, ArColor.getCPtr(primaryColor), primaryColor, size, layer, defaultRefreshTime, visibility), true);
  }

  public ArDrawingData(String shape, ArColor primaryColor, int size, int layer, long defaultRefreshTime) {
    this(AriaJavaJNI.new_ArDrawingData__SWIG_1(shape, ArColor.getCPtr(primaryColor), primaryColor, size, layer, defaultRefreshTime), true);
  }

  public ArDrawingData(String shape, ArColor primaryColor, int size, int layer) {
    this(AriaJavaJNI.new_ArDrawingData__SWIG_2(shape, ArColor.getCPtr(primaryColor), primaryColor, size, layer), true);
  }

  public ArDrawingData(String shape, ArColor primaryColor, int size, int layer, long defaultRefreshTime, ArColor secondaryColor, String visibility) {
    this(AriaJavaJNI.new_ArDrawingData__SWIG_3(shape, ArColor.getCPtr(primaryColor), primaryColor, size, layer, defaultRefreshTime, ArColor.getCPtr(secondaryColor), secondaryColor, visibility), true);
  }

  public ArDrawingData(String shape, ArColor primaryColor, int size, int layer, long defaultRefreshTime, ArColor secondaryColor) {
    this(AriaJavaJNI.new_ArDrawingData__SWIG_4(shape, ArColor.getCPtr(primaryColor), primaryColor, size, layer, defaultRefreshTime, ArColor.getCPtr(secondaryColor), secondaryColor), true);
  }

  public String getShape() {
    return AriaJavaJNI.ArDrawingData_getShape(swigCPtr, this);
  }

  public ArColor getPrimaryColor() {
    return new ArColor(AriaJavaJNI.ArDrawingData_getPrimaryColor(swigCPtr, this), true);
  }

  public int getSize() {
    return AriaJavaJNI.ArDrawingData_getSize(swigCPtr, this);
  }

  public int getLayer() {
    return AriaJavaJNI.ArDrawingData_getLayer(swigCPtr, this);
  }

  public long getDefaultRefreshTime() {
    return AriaJavaJNI.ArDrawingData_getDefaultRefreshTime(swigCPtr, this);
  }

  public ArColor getSecondaryColor() {
    return new ArColor(AriaJavaJNI.ArDrawingData_getSecondaryColor(swigCPtr, this), true);
  }

  public String getVisibility() {
    return AriaJavaJNI.ArDrawingData_getVisibility(swigCPtr, this);
  }

  public void setShape(String shape) {
    AriaJavaJNI.ArDrawingData_setShape(swigCPtr, this, shape);
  }

  public void setPrimaryColor(ArColor color) {
    AriaJavaJNI.ArDrawingData_setPrimaryColor(swigCPtr, this, ArColor.getCPtr(color), color);
  }

  public void setSize(int size) {
    AriaJavaJNI.ArDrawingData_setSize(swigCPtr, this, size);
  }

  public void setLayer(int layer) {
    AriaJavaJNI.ArDrawingData_setLayer(swigCPtr, this, layer);
  }

  public void setDefaultRefreshTime(long refreshTime) {
    AriaJavaJNI.ArDrawingData_setDefaultRefreshTime(swigCPtr, this, refreshTime);
  }

  public void setSecondaryColor(ArColor color) {
    AriaJavaJNI.ArDrawingData_setSecondaryColor(swigCPtr, this, ArColor.getCPtr(color), color);
  }

  public void setVisibility(String visibility) {
    AriaJavaJNI.ArDrawingData_setVisibility(swigCPtr, this, visibility);
  }

  public final static int DEFAULT_REFRESH_TIME = AriaJavaJNI.ArDrawingData_DEFAULT_REFRESH_TIME_get();

}
