/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArENUCoords extends Ar3DPoint {
  /* (begin code from javabody_derived typemap) */

  private long swigCPtr;

  /* for internal use by swig only */
  public ArENUCoords(long cPtr, boolean cMemoryOwn) {
    super(AriaJavaJNI.SWIGArENUCoordsUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArENUCoords obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody_derived typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArENUCoords(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ArENUCoords(double x, double y, double z) {
    this(AriaJavaJNI.new_ArENUCoords(x, y, z), true);
  }

  public ArECEFCoords ENU2ECEF(ArLLACoords ref) {
    return new ArECEFCoords(AriaJavaJNI.ArENUCoords_ENU2ECEF(swigCPtr, this, ArLLACoords.getCPtr(ref), ref), true);
  }

  public double getEast() {
    return AriaJavaJNI.ArENUCoords_getEast(swigCPtr, this);
  }

  public double getNorth() {
    return AriaJavaJNI.ArENUCoords_getNorth(swigCPtr, this);
  }

  public double getUp() {
    return AriaJavaJNI.ArENUCoords_getUp(swigCPtr, this);
  }

}
