/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArFunctor1_ArRobotPacketP extends ArFunctor {
  /* (begin code from javabody_derived typemap) */

  private long swigCPtr;

  /* for internal use by swig only */
  public ArFunctor1_ArRobotPacketP(long cPtr, boolean cMemoryOwn) {
    super(AriaJavaJNI.SWIGArFunctor1_ArRobotPacketPUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArFunctor1_ArRobotPacketP obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody_derived typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArFunctor1_ArRobotPacketP(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    AriaJavaJNI.ArFunctor1_ArRobotPacketP_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    AriaJavaJNI.ArFunctor1_ArRobotPacketP_change_ownership(this, swigCPtr, true);
  }

  public void invoke() {
    AriaJavaJNI.ArFunctor1_ArRobotPacketP_invoke__SWIG_0(swigCPtr, this);
  }

  public void invoke(ArRobotPacket p1) {
    AriaJavaJNI.ArFunctor1_ArRobotPacketP_invoke__SWIG_1(swigCPtr, this, ArRobotPacket.getCPtr(p1), p1);
  }

  public ArFunctor1_ArRobotPacketP() {
    this(AriaJavaJNI.new_ArFunctor1_ArRobotPacketP(), true);
    AriaJavaJNI.ArFunctor1_ArRobotPacketP_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
