/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArFunctor1_Int extends ArFunctor {
  /* (begin code from javabody_derived typemap) */

  private long swigCPtr;

  /* for internal use by swig only */
  public ArFunctor1_Int(long cPtr, boolean cMemoryOwn) {
    super(AriaJavaJNI.SWIGArFunctor1_IntUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArFunctor1_Int obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody_derived typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArFunctor1_Int(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void invoke() {
    AriaJavaJNI.ArFunctor1_Int_invoke__SWIG_0(swigCPtr, this);
  }

  public void invoke(int p1) {
    AriaJavaJNI.ArFunctor1_Int_invoke__SWIG_1(swigCPtr, this, p1);
  }

}
