/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArFunctorPtrList {
  /* (begin code from javabody typemap) */

  private long swigCPtr;
  protected boolean swigCMemOwn;

  /* for internal use by swig only */
  public ArFunctorPtrList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArFunctorPtrList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArFunctorPtrList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ArFunctorPtrList() {
    this(AriaJavaJNI.new_ArFunctorPtrList(), true);
  }

  public long size() {
    return AriaJavaJNI.ArFunctorPtrList_size(swigCPtr, this);
  }

  public boolean isEmpty() {
    return AriaJavaJNI.ArFunctorPtrList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    AriaJavaJNI.ArFunctorPtrList_clear(swigCPtr, this);
  }

  public void add(ArFunctor x) {
    AriaJavaJNI.ArFunctorPtrList_add(swigCPtr, this, ArFunctor.getCPtr(x), x);
  }

  public ArFunctor get(int i) {
    long cPtr = AriaJavaJNI.ArFunctorPtrList_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new ArFunctor(cPtr, false);
  }

}
