/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public interface AriaJavaConstants {
  public final static int _GNU_SOURCE = AriaJavaJNI._GNU_SOURCE_get();
  public final static double M_PI = AriaJavaJNI.M_PI_get();
  public final static String ARMAP_DEFAULT_SCAN_TYPE = AriaJavaJNI.ARMAP_DEFAULT_SCAN_TYPE_get();
  public final static String ARTCM2_DEFAULT_SERIAL_PORT = AriaJavaJNI.ARTCM2_DEFAULT_SERIAL_PORT_get();
  public final static int MAX_RESPONSE_BYTES = AriaJavaJNI.MAX_RESPONSE_BYTES_get();
  public final static int BIDIRECTIONAL_TIMEOUT = AriaJavaJNI.BIDIRECTIONAL_TIMEOUT_get();
  public final static int UNIDIRECTIONAL_TIMEOUT = AriaJavaJNI.UNIDIRECTIONAL_TIMEOUT_get();
  public final static int AUTO_UPDATE_TIME = AriaJavaJNI.AUTO_UPDATE_TIME_get();
  public final static double TOLERANCE = AriaJavaJNI.TOLERANCE_get();
}
