/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArInterpolation {
  /* (begin code from javabody typemap) */

  private long swigCPtr;
  protected boolean swigCMemOwn;

  /* for internal use by swig only */
  public ArInterpolation(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArInterpolation obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArInterpolation(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ArInterpolation(long numberOfReadings) {
    this(AriaJavaJNI.new_ArInterpolation__SWIG_0(numberOfReadings), true);
  }

  public ArInterpolation() {
    this(AriaJavaJNI.new_ArInterpolation__SWIG_1(), true);
  }

  public boolean addReading(ArTime timeOfReading, ArPose position) {
    return AriaJavaJNI.ArInterpolation_addReading(swigCPtr, this, ArTime.getCPtr(timeOfReading), timeOfReading, ArPose.getCPtr(position), position);
  }

  public int getPose(ArTime timeStamp, ArPose position) {
    return AriaJavaJNI.ArInterpolation_getPose(swigCPtr, this, ArTime.getCPtr(timeStamp), timeStamp, ArPose.getCPtr(position), position);
  }

  public void setNumberOfReadings(long numberOfReadings) {
    AriaJavaJNI.ArInterpolation_setNumberOfReadings(swigCPtr, this, numberOfReadings);
  }

  public long getNumberOfReadings() {
    return AriaJavaJNI.ArInterpolation_getNumberOfReadings(swigCPtr, this);
  }

  public void reset() {
    AriaJavaJNI.ArInterpolation_reset(swigCPtr, this);
  }

}
