/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArIRs extends ArRangeDevice {
  /* (begin code from javabody_derived typemap) */

  private long swigCPtr;

  /* for internal use by swig only */
  public ArIRs(long cPtr, boolean cMemoryOwn) {
    super(AriaJavaJNI.SWIGArIRsUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArIRs obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody_derived typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArIRs(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ArIRs(long currentBufferSize, long cumulativeBufferSize, String name, int maxSecondsToKeepCurrent) {
    this(AriaJavaJNI.new_ArIRs__SWIG_0(currentBufferSize, cumulativeBufferSize, name, maxSecondsToKeepCurrent), true);
  }

  public ArIRs(long currentBufferSize, long cumulativeBufferSize, String name) {
    this(AriaJavaJNI.new_ArIRs__SWIG_1(currentBufferSize, cumulativeBufferSize, name), true);
  }

  public ArIRs(long currentBufferSize, long cumulativeBufferSize) {
    this(AriaJavaJNI.new_ArIRs__SWIG_2(currentBufferSize, cumulativeBufferSize), true);
  }

  public ArIRs(long currentBufferSize) {
    this(AriaJavaJNI.new_ArIRs__SWIG_3(currentBufferSize), true);
  }

  public ArIRs() {
    this(AriaJavaJNI.new_ArIRs__SWIG_4(), true);
  }

  public void setRobot(ArRobot robot) {
    AriaJavaJNI.ArIRs_setRobot(swigCPtr, this, ArRobot.getCPtr(robot), robot);
  }

  public void processReadings() {
    AriaJavaJNI.ArIRs_processReadings(swigCPtr, this);
  }

}
