/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArJoyVec3f {
  /* (begin code from javabody typemap) */

  private long swigCPtr;
  protected boolean swigCMemOwn;

  /* for internal use by swig only */
  public ArJoyVec3f(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArJoyVec3f obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArJoyVec3f(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX(double value) {
    AriaJavaJNI.ArJoyVec3f_x_set(swigCPtr, this, value);
  }

  public double getX() {
    return AriaJavaJNI.ArJoyVec3f_x_get(swigCPtr, this);
  }

  public void setY(double value) {
    AriaJavaJNI.ArJoyVec3f_y_set(swigCPtr, this, value);
  }

  public double getY() {
    return AriaJavaJNI.ArJoyVec3f_y_get(swigCPtr, this);
  }

  public void setZ(double value) {
    AriaJavaJNI.ArJoyVec3f_z_set(swigCPtr, this, value);
  }

  public double getZ() {
    return AriaJavaJNI.ArJoyVec3f_z_get(swigCPtr, this);
  }

  public ArJoyVec3f() {
    this(AriaJavaJNI.new_ArJoyVec3f(), true);
  }

}
