/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArJoyVec3i {
  /* (begin code from javabody typemap) */

  private long swigCPtr;
  protected boolean swigCMemOwn;

  /* for internal use by swig only */
  public ArJoyVec3i(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArJoyVec3i obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArJoyVec3i(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public void setX(int value) {
    AriaJavaJNI.ArJoyVec3i_x_set(swigCPtr, this, value);
  }

  public int getX() {
    return AriaJavaJNI.ArJoyVec3i_x_get(swigCPtr, this);
  }

  public void setY(int value) {
    AriaJavaJNI.ArJoyVec3i_y_set(swigCPtr, this, value);
  }

  public int getY() {
    return AriaJavaJNI.ArJoyVec3i_y_get(swigCPtr, this);
  }

  public void setZ(int value) {
    AriaJavaJNI.ArJoyVec3i_z_set(swigCPtr, this, value);
  }

  public int getZ() {
    return AriaJavaJNI.ArJoyVec3i_z_get(swigCPtr, this);
  }

  public ArJoyVec3i() {
    this(AriaJavaJNI.new_ArJoyVec3i(), true);
  }

}
