/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArLineSegmentPtrList {
  /* (begin code from javabody typemap) */

  private long swigCPtr;
  protected boolean swigCMemOwn;

  /* for internal use by swig only */
  public ArLineSegmentPtrList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArLineSegmentPtrList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArLineSegmentPtrList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ArLineSegmentPtrList() {
    this(AriaJavaJNI.new_ArLineSegmentPtrList(), true);
  }

  public long size() {
    return AriaJavaJNI.ArLineSegmentPtrList_size(swigCPtr, this);
  }

  public boolean isEmpty() {
    return AriaJavaJNI.ArLineSegmentPtrList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    AriaJavaJNI.ArLineSegmentPtrList_clear(swigCPtr, this);
  }

  public void add(ArLineSegment x) {
    AriaJavaJNI.ArLineSegmentPtrList_add(swigCPtr, this, ArLineSegment.getCPtr(x), x);
  }

  public ArLineSegment get(int i) {
    long cPtr = AriaJavaJNI.ArLineSegmentPtrList_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new ArLineSegment(cPtr, false);
  }

}
