/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArLineSegmentList {
  /* (begin code from javabody typemap) */

  private long swigCPtr;
  protected boolean swigCMemOwn;

  /* for internal use by swig only */
  public ArLineSegmentList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArLineSegmentList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArLineSegmentList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ArLineSegmentList() {
    this(AriaJavaJNI.new_ArLineSegmentList(), true);
  }

  public long size() {
    return AriaJavaJNI.ArLineSegmentList_size(swigCPtr, this);
  }

  public boolean isEmpty() {
    return AriaJavaJNI.ArLineSegmentList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    AriaJavaJNI.ArLineSegmentList_clear(swigCPtr, this);
  }

  public void add(ArLineSegment x) {
    AriaJavaJNI.ArLineSegmentList_add(swigCPtr, this, ArLineSegment.getCPtr(x), x);
  }

  public ArLineSegment get(int i) {
    return new ArLineSegment(AriaJavaJNI.ArLineSegmentList_get(swigCPtr, this, i), false);
  }

}
