/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArLLACoords extends Ar3DPoint {
  /* (begin code from javabody_derived typemap) */

  private long swigCPtr;

  /* for internal use by swig only */
  public ArLLACoords(long cPtr, boolean cMemoryOwn) {
    super(AriaJavaJNI.SWIGArLLACoordsUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArLLACoords obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody_derived typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArLLACoords(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ArLLACoords() {
    this(AriaJavaJNI.new_ArLLACoords__SWIG_0(), true);
  }

  public ArLLACoords(double x, double y, double z) {
    this(AriaJavaJNI.new_ArLLACoords__SWIG_1(x, y, z), true);
  }

  public ArECEFCoords LLA2ECEF() {
    return new ArECEFCoords(AriaJavaJNI.ArLLACoords_LLA2ECEF(swigCPtr, this), true);
  }

  public double getLatitude() {
    return AriaJavaJNI.ArLLACoords_getLatitude(swigCPtr, this);
  }

  public double getLongitude() {
    return AriaJavaJNI.ArLLACoords_getLongitude(swigCPtr, this);
  }

  public double getAltitude() {
    return AriaJavaJNI.ArLLACoords_getAltitude(swigCPtr, this);
  }

}
