/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArMapSupplement extends ArMapSupplementInterface {
  /* (begin code from javabody_derived typemap) */

  private long swigCPtr;

  /* for internal use by swig only */
  public ArMapSupplement(long cPtr, boolean cMemoryOwn) {
    super(AriaJavaJNI.SWIGArMapSupplementUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArMapSupplement obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody_derived typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArMapSupplement(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ArMapSupplement() {
    this(AriaJavaJNI.new_ArMapSupplement__SWIG_0(), true);
  }

  public ArMapSupplement(ArMapSupplement other) {
    this(AriaJavaJNI.new_ArMapSupplement__SWIG_1(ArMapSupplement.getCPtr(other), other), true);
  }

  public boolean hasOriginLatLongAlt() {
    return AriaJavaJNI.ArMapSupplement_hasOriginLatLongAlt(swigCPtr, this);
  }

  public ArPose getOriginLatLong() {
    return new ArPose(AriaJavaJNI.ArMapSupplement_getOriginLatLong(swigCPtr, this), true);
  }

  public double getOriginAltitude() {
    return AriaJavaJNI.ArMapSupplement_getOriginAltitude(swigCPtr, this);
  }

  public void setOriginLatLongAlt(boolean hasOriginLatLong, ArPose originLatLong, double altitude, SWIGTYPE_p_ArMapChangeDetails changeDetails) {
    AriaJavaJNI.ArMapSupplement_setOriginLatLongAlt__SWIG_0(swigCPtr, this, hasOriginLatLong, ArPose.getCPtr(originLatLong), originLatLong, altitude, SWIGTYPE_p_ArMapChangeDetails.getCPtr(changeDetails));
  }

  public void setOriginLatLongAlt(boolean hasOriginLatLong, ArPose originLatLong, double altitude) {
    AriaJavaJNI.ArMapSupplement_setOriginLatLongAlt__SWIG_1(swigCPtr, this, hasOriginLatLong, ArPose.getCPtr(originLatLong), originLatLong, altitude);
  }

  public void writeSupplementToFunctor(ArFunctor1_CString functor, String endOfLineChars) {
    AriaJavaJNI.ArMapSupplement_writeSupplementToFunctor(swigCPtr, this, ArFunctor1_CString.getCPtr(functor), functor, endOfLineChars);
  }

  public void clear() {
    AriaJavaJNI.ArMapSupplement_clear(swigCPtr, this);
  }

  public boolean addToFileParser(ArFileParser fileParser) {
    return AriaJavaJNI.ArMapSupplement_addToFileParser(swigCPtr, this, ArFileParser.getCPtr(fileParser), fileParser);
  }

  public boolean remFromFileParser(ArFileParser fileParser) {
    return AriaJavaJNI.ArMapSupplement_remFromFileParser(swigCPtr, this, ArFileParser.getCPtr(fileParser), fileParser);
  }

  public ArTime getTimeChanged() {
    return new ArTime(AriaJavaJNI.ArMapSupplement_getTimeChanged(swigCPtr, this), true);
  }

}
