/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArMapObjectPtrList {
  /* (begin code from javabody typemap) */

  private long swigCPtr;
  protected boolean swigCMemOwn;

  /* for internal use by swig only */
  public ArMapObjectPtrList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArMapObjectPtrList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArMapObjectPtrList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ArMapObjectPtrList() {
    this(AriaJavaJNI.new_ArMapObjectPtrList(), true);
  }

  public long size() {
    return AriaJavaJNI.ArMapObjectPtrList_size(swigCPtr, this);
  }

  public boolean isEmpty() {
    return AriaJavaJNI.ArMapObjectPtrList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    AriaJavaJNI.ArMapObjectPtrList_clear(swigCPtr, this);
  }

  public void add(ArMapObject x) {
    AriaJavaJNI.ArMapObjectPtrList_add(swigCPtr, this, ArMapObject.getCPtr(x), x);
  }

  public ArMapObject get(int i) {
    long cPtr = AriaJavaJNI.ArMapObjectPtrList_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new ArMapObject(cPtr, false);
  }

}
