/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArMath {
  /* (begin code from javabody typemap) */

  private long swigCPtr;
  protected boolean swigCMemOwn;

  /* for internal use by swig only */
  public ArMath(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArMath obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArMath(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static double epsilon() {
    return AriaJavaJNI.ArMath_epsilon();
  }

  public static double addAngle(double ang1, double ang2) {
    return AriaJavaJNI.ArMath_addAngle(ang1, ang2);
  }

  public static double subAngle(double ang1, double ang2) {
    return AriaJavaJNI.ArMath_subAngle(ang1, ang2);
  }

  public static double fixAngle(double angle) {
    return AriaJavaJNI.ArMath_fixAngle(angle);
  }

  public static double degToRad(double deg) {
    return AriaJavaJNI.ArMath_degToRad(deg);
  }

  public static double radToDeg(double rad) {
    return AriaJavaJNI.ArMath_radToDeg(rad);
  }

  public static double cos(double angle) {
    return AriaJavaJNI.ArMath_cos(angle);
  }

  public static double sin(double angle) {
    return AriaJavaJNI.ArMath_sin(angle);
  }

  public static double tan(double angle) {
    return AriaJavaJNI.ArMath_tan(angle);
  }

  public static double atan2(double y, double x) {
    return AriaJavaJNI.ArMath_atan2(y, x);
  }

  public static boolean angleBetween(double angle, double startAngle, double endAngle) {
    return AriaJavaJNI.ArMath_angleBetween(angle, startAngle, endAngle);
  }

  public static double fabs(double val) {
    return AriaJavaJNI.ArMath_fabs(val);
  }

  public static int roundInt(double val) {
    return AriaJavaJNI.ArMath_roundInt(val);
  }

  public static short roundShort(double val) {
    return AriaJavaJNI.ArMath_roundShort(val);
  }

  public static void pointRotate(double[] x, double[] y, double th) {
    AriaJavaJNI.ArMath_pointRotate(x, y, th);
  }

  public static int random() {
    return AriaJavaJNI.ArMath_random();
  }

  public static int getRandMax() {
    return AriaJavaJNI.ArMath_getRandMax();
  }

  public static int randomInRange(int m, int n) {
    return AriaJavaJNI.ArMath_randomInRange(m, n);
  }

  public static double distanceBetween(double x1, double y1, double x2, double y2) {
    return AriaJavaJNI.ArMath_distanceBetween(x1, y1, x2, y2);
  }

  public static double squaredDistanceBetween(double x1, double y1, double x2, double y2) {
    return AriaJavaJNI.ArMath_squaredDistanceBetween(x1, y1, x2, y2);
  }

  public static double log2(double x) {
    return AriaJavaJNI.ArMath_log2(x);
  }

  public static boolean isNan(double d) {
    return AriaJavaJNI.ArMath_isNan(d);
  }

  public ArMath() {
    this(AriaJavaJNI.new_ArMath(), true);
  }

}
