/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArMD5Calculator {
  /* (begin code from javabody typemap) */

  private long swigCPtr;
  protected boolean swigCMemOwn;

  /* for internal use by swig only */
  public ArMD5Calculator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArMD5Calculator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArMD5Calculator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static void toDisplay(SWIGTYPE_p_unsigned_char digestBuf, long digestLength, String displayBuf, long displayLength) {
    AriaJavaJNI.ArMD5Calculator_toDisplay(SWIGTYPE_p_unsigned_char.getCPtr(digestBuf), digestLength, displayBuf, displayLength);
  }

  public static boolean calculateChecksum(String fileName, SWIGTYPE_p_unsigned_char md5DigestBuffer, long md5DigestBufferLen) {
    return AriaJavaJNI.ArMD5Calculator_calculateChecksum(fileName, SWIGTYPE_p_unsigned_char.getCPtr(md5DigestBuffer), md5DigestBufferLen);
  }

  public ArMD5Calculator(ArFunctor1_CString secondFunctor) {
    this(AriaJavaJNI.new_ArMD5Calculator__SWIG_0(ArFunctor1_CString.getCPtr(secondFunctor), secondFunctor), true);
  }

  public ArMD5Calculator() {
    this(AriaJavaJNI.new_ArMD5Calculator__SWIG_1(), true);
  }

  public void reset() {
    AriaJavaJNI.ArMD5Calculator_reset(swigCPtr, this);
  }

  public void append(String str) {
    AriaJavaJNI.ArMD5Calculator_append(swigCPtr, this, str);
  }

  public SWIGTYPE_p_unsigned_char getDigest() {
    long cPtr = AriaJavaJNI.ArMD5Calculator_getDigest(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_unsigned_char(cPtr, false);
  }

  public ArFunctor1_CString getFunctor() {
    long cPtr = AriaJavaJNI.ArMD5Calculator_getFunctor(swigCPtr, this);
    return (cPtr == 0) ? null : new ArFunctor1_CString(cPtr, false);
  }

  public ArFunctor1_CString getSecondFunctor() {
    long cPtr = AriaJavaJNI.ArMD5Calculator_getSecondFunctor(swigCPtr, this);
    return (cPtr == 0) ? null : new ArFunctor1_CString(cPtr, false);
  }

  public void setSecondFunctor(ArFunctor1_CString secondFunctor) {
    AriaJavaJNI.ArMD5Calculator_setSecondFunctor(swigCPtr, this, ArFunctor1_CString.getCPtr(secondFunctor), secondFunctor);
  }

  public final static int DIGEST_LENGTH = AriaJavaJNI.ArMD5Calculator_DIGEST_LENGTH_get();
  public final static int DISPLAY_LENGTH = AriaJavaJNI.ArMD5Calculator_DISPLAY_LENGTH_get();

}
