/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArMode {
  /* (begin code from javabody typemap) */

  private long swigCPtr;
  protected boolean swigCMemOwn;

  /* for internal use by swig only */
  public ArMode(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArMode obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArMode(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public String getName() {
    return AriaJavaJNI.ArMode_getName(swigCPtr, this);
  }

  public void activate() {
    AriaJavaJNI.ArMode_activate(swigCPtr, this);
  }

  public void deactivate() {
    AriaJavaJNI.ArMode_deactivate(swigCPtr, this);
  }

  public void userTask() {
    AriaJavaJNI.ArMode_userTask(swigCPtr, this);
  }

  public void help() {
    AriaJavaJNI.ArMode_help(swigCPtr, this);
  }

  public boolean baseActivate() {
    return AriaJavaJNI.ArMode_baseActivate(swigCPtr, this);
  }

  public boolean baseDeactivate() {
    return AriaJavaJNI.ArMode_baseDeactivate(swigCPtr, this);
  }

  public static void baseHelp() {
    AriaJavaJNI.ArMode_baseHelp();
  }

  public char getKey() {
    return AriaJavaJNI.ArMode_getKey(swigCPtr, this);
  }

  public char getKey2() {
    return AriaJavaJNI.ArMode_getKey2(swigCPtr, this);
  }

}
