/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArModeCamera extends ArMode {
  /* (begin code from javabody_derived typemap) */

  private long swigCPtr;

  /* for internal use by swig only */
  public ArModeCamera(long cPtr, boolean cMemoryOwn) {
    super(AriaJavaJNI.SWIGArModeCameraUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArModeCamera obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody_derived typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArModeCamera(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ArModeCamera(ArRobot robot, String name, char key, char key2) {
    this(AriaJavaJNI.new_ArModeCamera(ArRobot.getCPtr(robot), robot, name, key, key2), true);
  }

  public void activate() {
    AriaJavaJNI.ArModeCamera_activate(swigCPtr, this);
  }

  public void deactivate() {
    AriaJavaJNI.ArModeCamera_deactivate(swigCPtr, this);
  }

  public void userTask() {
    AriaJavaJNI.ArModeCamera_userTask(swigCPtr, this);
  }

  public void help() {
    AriaJavaJNI.ArModeCamera_help(swigCPtr, this);
  }

  public void up() {
    AriaJavaJNI.ArModeCamera_up(swigCPtr, this);
  }

  public void down() {
    AriaJavaJNI.ArModeCamera_down(swigCPtr, this);
  }

  public void left() {
    AriaJavaJNI.ArModeCamera_left(swigCPtr, this);
  }

  public void right() {
    AriaJavaJNI.ArModeCamera_right(swigCPtr, this);
  }

  public void center() {
    AriaJavaJNI.ArModeCamera_center(swigCPtr, this);
  }

  public void zoomIn() {
    AriaJavaJNI.ArModeCamera_zoomIn(swigCPtr, this);
  }

  public void zoomOut() {
    AriaJavaJNI.ArModeCamera_zoomOut(swigCPtr, this);
  }

  public void exercise() {
    AriaJavaJNI.ArModeCamera_exercise(swigCPtr, this);
  }

  public void sony() {
    AriaJavaJNI.ArModeCamera_sony(swigCPtr, this);
  }

  public void canon() {
    AriaJavaJNI.ArModeCamera_canon(swigCPtr, this);
  }

  public void dpptu() {
    AriaJavaJNI.ArModeCamera_dpptu(swigCPtr, this);
  }

  public void amptu() {
    AriaJavaJNI.ArModeCamera_amptu(swigCPtr, this);
  }

  public void canonInverted() {
    AriaJavaJNI.ArModeCamera_canonInverted(swigCPtr, this);
  }

  public void sonySerial() {
    AriaJavaJNI.ArModeCamera_sonySerial(swigCPtr, this);
  }

  public void canonSerial() {
    AriaJavaJNI.ArModeCamera_canonSerial(swigCPtr, this);
  }

  public void dpptuSerial() {
    AriaJavaJNI.ArModeCamera_dpptuSerial(swigCPtr, this);
  }

  public void amptuSerial() {
    AriaJavaJNI.ArModeCamera_amptuSerial(swigCPtr, this);
  }

  public void canonInvertedSerial() {
    AriaJavaJNI.ArModeCamera_canonInvertedSerial(swigCPtr, this);
  }

  public void rvisionSerial() {
    AriaJavaJNI.ArModeCamera_rvisionSerial(swigCPtr, this);
  }

  public void com1() {
    AriaJavaJNI.ArModeCamera_com1(swigCPtr, this);
  }

  public void com2() {
    AriaJavaJNI.ArModeCamera_com2(swigCPtr, this);
  }

  public void com3() {
    AriaJavaJNI.ArModeCamera_com3(swigCPtr, this);
  }

  public void com4() {
    AriaJavaJNI.ArModeCamera_com4(swigCPtr, this);
  }

  public void aux1() {
    AriaJavaJNI.ArModeCamera_aux1(swigCPtr, this);
  }

  public void aux2() {
    AriaJavaJNI.ArModeCamera_aux2(swigCPtr, this);
  }

}
