/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArModule {
  /* (begin code from javabody typemap) */

  private long swigCPtr;
  protected boolean swigCMemOwn;

  /* for internal use by swig only */
  public ArModule(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArModule obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArModule(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean init(ArRobot robot, SWIGTYPE_p_void argument) {
    return AriaJavaJNI.ArModule_init__SWIG_0(swigCPtr, this, ArRobot.getCPtr(robot), robot, SWIGTYPE_p_void.getCPtr(argument));
  }

  public boolean init(ArRobot robot) {
    return AriaJavaJNI.ArModule_init__SWIG_1(swigCPtr, this, ArRobot.getCPtr(robot), robot);
  }

  public boolean exit() {
    return AriaJavaJNI.ArModule_exit(swigCPtr, this);
  }

  public ArRobot getRobot() {
    long cPtr = AriaJavaJNI.ArModule_getRobot(swigCPtr, this);
    return (cPtr == 0) ? null : new ArRobot(cPtr, false);
  }

  public void setRobot(ArRobot robot) {
    AriaJavaJNI.ArModule_setRobot(swigCPtr, this, ArRobot.getCPtr(robot), robot);
  }

}
