/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArModeWander extends ArMode {
  /* (begin code from javabody_derived typemap) */

  private long swigCPtr;

  /* for internal use by swig only */
  public ArModeWander(long cPtr, boolean cMemoryOwn) {
    super(AriaJavaJNI.SWIGArModeWanderUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArModeWander obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody_derived typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArModeWander(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ArModeWander(ArRobot robot, String name, char key, char key2) {
    this(AriaJavaJNI.new_ArModeWander(ArRobot.getCPtr(robot), robot, name, key, key2), true);
  }

  public void activate() {
    AriaJavaJNI.ArModeWander_activate(swigCPtr, this);
  }

  public void deactivate() {
    AriaJavaJNI.ArModeWander_deactivate(swigCPtr, this);
  }

  public void help() {
    AriaJavaJNI.ArModeWander_help(swigCPtr, this);
  }

  public void userTask() {
    AriaJavaJNI.ArModeWander_userTask(swigCPtr, this);
  }

}
