/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArModeTCM2 extends ArMode {
  /* (begin code from javabody_derived typemap) */

  private long swigCPtr;

  /* for internal use by swig only */
  public ArModeTCM2(long cPtr, boolean cMemoryOwn) {
    super(AriaJavaJNI.SWIGArModeTCM2Upcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArModeTCM2 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody_derived typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArModeTCM2(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ArModeTCM2(ArRobot robot, String name, char key, char key2, ArTCM2 tcm2) {
    this(AriaJavaJNI.new_ArModeTCM2__SWIG_0(ArRobot.getCPtr(robot), robot, name, key, key2, ArTCM2.getCPtr(tcm2), tcm2), true);
  }

  public ArModeTCM2(ArRobot robot, String name, char key, char key2) {
    this(AriaJavaJNI.new_ArModeTCM2__SWIG_1(ArRobot.getCPtr(robot), robot, name, key, key2), true);
  }

  public void activate() {
    AriaJavaJNI.ArModeTCM2_activate(swigCPtr, this);
  }

  public void deactivate() {
    AriaJavaJNI.ArModeTCM2_deactivate(swigCPtr, this);
  }

  public void help() {
    AriaJavaJNI.ArModeTCM2_help(swigCPtr, this);
  }

  public void userTask() {
    AriaJavaJNI.ArModeTCM2_userTask(swigCPtr, this);
  }

}
