/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArNovatelSPAN extends ArNovatelGPS {
  /* (begin code from javabody_derived typemap) */

  private long swigCPtr;

  /* for internal use by swig only */
  public ArNovatelSPAN(long cPtr, boolean cMemoryOwn) {
    super(AriaJavaJNI.SWIGArNovatelSPANUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArNovatelSPAN obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody_derived typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArNovatelSPAN(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void setGPSLatitude(double value) {
    AriaJavaJNI.ArNovatelSPAN_GPSLatitude_set(swigCPtr, this, value);
  }

  public double getGPSLatitude() {
    return AriaJavaJNI.ArNovatelSPAN_GPSLatitude_get(swigCPtr, this);
  }

  public void setGPSLongitude(double value) {
    AriaJavaJNI.ArNovatelSPAN_GPSLongitude_set(swigCPtr, this, value);
  }

  public double getGPSLongitude() {
    return AriaJavaJNI.ArNovatelSPAN_GPSLongitude_get(swigCPtr, this);
  }

  public void setHaveGPSPosition(boolean value) {
    AriaJavaJNI.ArNovatelSPAN_haveGPSPosition_set(swigCPtr, this, value);
  }

  public boolean getHaveGPSPosition() {
    return AriaJavaJNI.ArNovatelSPAN_haveGPSPosition_get(swigCPtr, this);
  }

  public void setGPSValidFlag(boolean value) {
    AriaJavaJNI.ArNovatelSPAN_GPSValidFlag_set(swigCPtr, this, value);
  }

  public boolean getGPSValidFlag() {
    return AriaJavaJNI.ArNovatelSPAN_GPSValidFlag_get(swigCPtr, this);
  }

  public void setTimeGotGPSPosition(ArTime value) {
    AriaJavaJNI.ArNovatelSPAN_timeGotGPSPosition_set(swigCPtr, this, ArTime.getCPtr(value), value);
  }

  public ArTime getTimeGotGPSPosition() {
    long cPtr = AriaJavaJNI.ArNovatelSPAN_timeGotGPSPosition_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ArTime(cPtr, false);
  }

  public void setGPSTimestamp(ArTime value) {
    AriaJavaJNI.ArNovatelSPAN_GPSTimestamp_set(swigCPtr, this, ArTime.getCPtr(value), value);
  }

  public ArTime getGPSTimestamp() {
    long cPtr = AriaJavaJNI.ArNovatelSPAN_GPSTimestamp_get(swigCPtr, this);
    return (cPtr == 0) ? null : new ArTime(cPtr, false);
  }

  public ArNovatelSPAN() {
    this(AriaJavaJNI.new_ArNovatelSPAN(), true);
  }

}
