/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArPoseWithTimeList {
  /* (begin code from javabody typemap) */

  private long swigCPtr;
  protected boolean swigCMemOwn;

  /* for internal use by swig only */
  public ArPoseWithTimeList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArPoseWithTimeList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArPoseWithTimeList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ArPoseWithTimeList() {
    this(AriaJavaJNI.new_ArPoseWithTimeList(), true);
  }

  public long size() {
    return AriaJavaJNI.ArPoseWithTimeList_size(swigCPtr, this);
  }

  public boolean isEmpty() {
    return AriaJavaJNI.ArPoseWithTimeList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    AriaJavaJNI.ArPoseWithTimeList_clear(swigCPtr, this);
  }

  public void add(ArPoseWithTime x) {
    AriaJavaJNI.ArPoseWithTimeList_add(swigCPtr, this, ArPoseWithTime.getCPtr(x), x);
  }

  public ArPoseWithTime get(int i) {
    return new ArPoseWithTime(AriaJavaJNI.ArPoseWithTimeList_get(swigCPtr, this, i), false);
  }

}
