/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArPosePtrList {
  /* (begin code from javabody typemap) */

  private long swigCPtr;
  protected boolean swigCMemOwn;

  /* for internal use by swig only */
  public ArPosePtrList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArPosePtrList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArPosePtrList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ArPosePtrList() {
    this(AriaJavaJNI.new_ArPosePtrList(), true);
  }

  public long size() {
    return AriaJavaJNI.ArPosePtrList_size(swigCPtr, this);
  }

  public boolean isEmpty() {
    return AriaJavaJNI.ArPosePtrList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    AriaJavaJNI.ArPosePtrList_clear(swigCPtr, this);
  }

  public void add(ArPose x) {
    AriaJavaJNI.ArPosePtrList_add(swigCPtr, this, ArPose.getCPtr(x), x);
  }

  public ArPose get(int i) {
    long cPtr = AriaJavaJNI.ArPosePtrList_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new ArPose(cPtr, false);
  }

}
