/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArPoseWithTimePtrList {
  /* (begin code from javabody typemap) */

  private long swigCPtr;
  protected boolean swigCMemOwn;

  /* for internal use by swig only */
  public ArPoseWithTimePtrList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArPoseWithTimePtrList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArPoseWithTimePtrList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ArPoseWithTimePtrList() {
    this(AriaJavaJNI.new_ArPoseWithTimePtrList(), true);
  }

  public long size() {
    return AriaJavaJNI.ArPoseWithTimePtrList_size(swigCPtr, this);
  }

  public boolean isEmpty() {
    return AriaJavaJNI.ArPoseWithTimePtrList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    AriaJavaJNI.ArPoseWithTimePtrList_clear(swigCPtr, this);
  }

  public void add(ArPoseWithTime x) {
    AriaJavaJNI.ArPoseWithTimePtrList_add(swigCPtr, this, ArPoseWithTime.getCPtr(x), x);
  }

  public ArPoseWithTime get(int i) {
    long cPtr = AriaJavaJNI.ArPoseWithTimePtrList_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new ArPoseWithTime(cPtr, false);
  }

}
