/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArRangeDevicePtrList {
  /* (begin code from javabody typemap) */

  private long swigCPtr;
  protected boolean swigCMemOwn;

  /* for internal use by swig only */
  public ArRangeDevicePtrList(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArRangeDevicePtrList obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArRangeDevicePtrList(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ArRangeDevicePtrList() {
    this(AriaJavaJNI.new_ArRangeDevicePtrList(), true);
  }

  public long size() {
    return AriaJavaJNI.ArRangeDevicePtrList_size(swigCPtr, this);
  }

  public boolean isEmpty() {
    return AriaJavaJNI.ArRangeDevicePtrList_isEmpty(swigCPtr, this);
  }

  public void clear() {
    AriaJavaJNI.ArRangeDevicePtrList_clear(swigCPtr, this);
  }

  public void add(ArRangeDevice x) {
    AriaJavaJNI.ArRangeDevicePtrList_add(swigCPtr, this, ArRangeDevice.getCPtr(x), x);
  }

  public ArRangeDevice get(int i) {
    long cPtr = AriaJavaJNI.ArRangeDevicePtrList_get(swigCPtr, this, i);
    return (cPtr == 0) ? null : new ArRangeDevice(cPtr, false);
  }

}
