/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArResolver {
  /* (begin code from javabody typemap) */

  private long swigCPtr;
  protected boolean swigCMemOwn;

  /* for internal use by swig only */
  public ArResolver(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArResolver obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArResolver(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ArActionDesired resolve(SWIGTYPE_p_std__multimapT_int_ArAction_p_t actions, ArRobot robot, boolean logActions) {
    long cPtr = AriaJavaJNI.ArResolver_resolve__SWIG_0(swigCPtr, this, SWIGTYPE_p_std__multimapT_int_ArAction_p_t.getCPtr(actions), ArRobot.getCPtr(robot), robot, logActions);
    return (cPtr == 0) ? null : new ArActionDesired(cPtr, false);
  }

  public ArActionDesired resolve(SWIGTYPE_p_std__multimapT_int_ArAction_p_t actions, ArRobot robot) {
    long cPtr = AriaJavaJNI.ArResolver_resolve__SWIG_1(swigCPtr, this, SWIGTYPE_p_std__multimapT_int_ArAction_p_t.getCPtr(actions), ArRobot.getCPtr(robot), robot);
    return (cPtr == 0) ? null : new ArActionDesired(cPtr, false);
  }

  public String getName() {
    return AriaJavaJNI.ArResolver_getName(swigCPtr, this);
  }

  public String getDescription() {
    return AriaJavaJNI.ArResolver_getDescription(swigCPtr, this);
  }

}
