/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArRetFunctor1_VoidP_VoidP extends ArRetFunctor_VoidP {
  /* (begin code from javabody_derived typemap) */

  private long swigCPtr;

  /* for internal use by swig only */
  public ArRetFunctor1_VoidP_VoidP(long cPtr, boolean cMemoryOwn) {
    super(AriaJavaJNI.SWIGArRetFunctor1_VoidP_VoidPUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArRetFunctor1_VoidP_VoidP obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody_derived typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArRetFunctor1_VoidP_VoidP(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    AriaJavaJNI.ArRetFunctor1_VoidP_VoidP_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    AriaJavaJNI.ArRetFunctor1_VoidP_VoidP_change_ownership(this, swigCPtr, true);
  }

  public SWIGTYPE_p_void invokeR() {
    long cPtr = AriaJavaJNI.ArRetFunctor1_VoidP_VoidP_invokeR__SWIG_0(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public SWIGTYPE_p_void invokeR(SWIGTYPE_p_void p1) {
    long cPtr = AriaJavaJNI.ArRetFunctor1_VoidP_VoidP_invokeR__SWIG_1(swigCPtr, this, SWIGTYPE_p_void.getCPtr(p1));
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public ArRetFunctor1_VoidP_VoidP() {
    this(AriaJavaJNI.new_ArRetFunctor1_VoidP_VoidP(), true);
    AriaJavaJNI.ArRetFunctor1_VoidP_VoidP_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
