/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArRetFunctor1_Bool_ArgumentBuilderP extends ArRetFunctor_Bool {
  /* (begin code from javabody_derived typemap) */

  private long swigCPtr;

  /* for internal use by swig only */
  public ArRetFunctor1_Bool_ArgumentBuilderP(long cPtr, boolean cMemoryOwn) {
    super(AriaJavaJNI.SWIGArRetFunctor1_Bool_ArgumentBuilderPUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArRetFunctor1_Bool_ArgumentBuilderP obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody_derived typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArRetFunctor1_Bool_ArgumentBuilderP(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  protected void swigDirectorDisconnect() {
    swigCMemOwn = false;
    delete();
  }

  public void swigReleaseOwnership() {
    swigCMemOwn = false;
    AriaJavaJNI.ArRetFunctor1_Bool_ArgumentBuilderP_change_ownership(this, swigCPtr, false);
  }

  public void swigTakeOwnership() {
    swigCMemOwn = true;
    AriaJavaJNI.ArRetFunctor1_Bool_ArgumentBuilderP_change_ownership(this, swigCPtr, true);
  }

  public boolean invokeR() {
    return AriaJavaJNI.ArRetFunctor1_Bool_ArgumentBuilderP_invokeR__SWIG_0(swigCPtr, this);
  }

  public boolean invokeR(ArArgumentBuilder p1) {
    return AriaJavaJNI.ArRetFunctor1_Bool_ArgumentBuilderP_invokeR__SWIG_1(swigCPtr, this, ArArgumentBuilder.getCPtr(p1), p1);
  }

  public ArRetFunctor1_Bool_ArgumentBuilderP() {
    this(AriaJavaJNI.new_ArRetFunctor1_Bool_ArgumentBuilderP(), true);
    AriaJavaJNI.ArRetFunctor1_Bool_ArgumentBuilderP_director_connect(this, swigCPtr, swigCMemOwn, true);
  }

}
