/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArRecurrentTask extends ArASyncTask {
  /* (begin code from javabody_derived typemap) */

  private long swigCPtr;

  /* for internal use by swig only */
  public ArRecurrentTask(long cPtr, boolean cMemoryOwn) {
    super(AriaJavaJNI.SWIGArRecurrentTaskUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArRecurrentTask obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody_derived typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArRecurrentTask(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public void task() {
    AriaJavaJNI.ArRecurrentTask_task(swigCPtr, this);
  }

  public void go() {
    AriaJavaJNI.ArRecurrentTask_go(swigCPtr, this);
  }

  public int done() {
    return AriaJavaJNI.ArRecurrentTask_done(swigCPtr, this);
  }

  public void reset() {
    AriaJavaJNI.ArRecurrentTask_reset(swigCPtr, this);
  }

  public void kill() {
    AriaJavaJNI.ArRecurrentTask_kill(swigCPtr, this);
  }

  public SWIGTYPE_p_void runThread(SWIGTYPE_p_void ptr) {
    long cPtr = AriaJavaJNI.ArRecurrentTask_runThread(swigCPtr, this, SWIGTYPE_p_void.getCPtr(ptr));
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

}
