/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArRobotPacket extends ArBasePacket {
  /* (begin code from javabody_derived typemap) */

  private long swigCPtr;

  /* for internal use by swig only */
  public ArRobotPacket(long cPtr, boolean cMemoryOwn) {
    super(AriaJavaJNI.SWIGArRobotPacketUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArRobotPacket obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody_derived typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArRobotPacket(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ArRobotPacket(short sync1, short sync2) {
    this(AriaJavaJNI.new_ArRobotPacket__SWIG_0(sync1, sync2), true);
  }

  public ArRobotPacket(short sync1) {
    this(AriaJavaJNI.new_ArRobotPacket__SWIG_1(sync1), true);
  }

  public ArRobotPacket() {
    this(AriaJavaJNI.new_ArRobotPacket__SWIG_2(), true);
  }

  public boolean verifyCheckSum() {
    return AriaJavaJNI.ArRobotPacket_verifyCheckSum(swigCPtr, this);
  }

  public short getID() {
    return AriaJavaJNI.ArRobotPacket_getID(swigCPtr, this);
  }

  public void setID(short id) {
    AriaJavaJNI.ArRobotPacket_setID(swigCPtr, this, id);
  }

  public short calcCheckSum() {
    return AriaJavaJNI.ArRobotPacket_calcCheckSum(swigCPtr, this);
  }

  public void finalizePacket() {
    AriaJavaJNI.ArRobotPacket_finalizePacket(swigCPtr, this);
  }

  public ArTime getTimeReceived() {
    return new ArTime(AriaJavaJNI.ArRobotPacket_getTimeReceived(swigCPtr, this), true);
  }

  public void setTimeReceived(ArTime timeReceived) {
    AriaJavaJNI.ArRobotPacket_setTimeReceived(swigCPtr, this, ArTime.getCPtr(timeReceived), timeReceived);
  }

  public void log() {
    AriaJavaJNI.ArRobotPacket_log(swigCPtr, this);
  }

}
