/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArRootMeanSquareCalculator {
  /* (begin code from javabody typemap) */

  private long swigCPtr;
  protected boolean swigCMemOwn;

  /* for internal use by swig only */
  public ArRootMeanSquareCalculator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArRootMeanSquareCalculator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArRootMeanSquareCalculator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ArRootMeanSquareCalculator() {
    this(AriaJavaJNI.new_ArRootMeanSquareCalculator(), true);
  }

  public double getRootMeanSquare() {
    return AriaJavaJNI.ArRootMeanSquareCalculator_getRootMeanSquare(swigCPtr, this);
  }

  public void add(int val) {
    AriaJavaJNI.ArRootMeanSquareCalculator_add(swigCPtr, this, val);
  }

  public void clear() {
    AriaJavaJNI.ArRootMeanSquareCalculator_clear(swigCPtr, this);
  }

  public void setName(String name) {
    AriaJavaJNI.ArRootMeanSquareCalculator_setName(swigCPtr, this, name);
  }

  public String getName() {
    return AriaJavaJNI.ArRootMeanSquareCalculator_getName(swigCPtr, this);
  }

  public long getCurrentNumAveraged() {
    return AriaJavaJNI.ArRootMeanSquareCalculator_getCurrentNumAveraged(swigCPtr, this);
  }

}
