/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArRunningAverage {
  /* (begin code from javabody typemap) */

  private long swigCPtr;
  protected boolean swigCMemOwn;

  /* for internal use by swig only */
  public ArRunningAverage(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArRunningAverage obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArRunningAverage(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ArRunningAverage(long numToAverage) {
    this(AriaJavaJNI.new_ArRunningAverage(numToAverage), true);
  }

  public double getAverage() {
    return AriaJavaJNI.ArRunningAverage_getAverage(swigCPtr, this);
  }

  public void add(double val) {
    AriaJavaJNI.ArRunningAverage_add(swigCPtr, this, val);
  }

  public void clear() {
    AriaJavaJNI.ArRunningAverage_clear(swigCPtr, this);
  }

  public long getNumToAverage() {
    return AriaJavaJNI.ArRunningAverage_getNumToAverage(swigCPtr, this);
  }

  public void setNumToAverage(long numToAverage) {
    AriaJavaJNI.ArRunningAverage_setNumToAverage(swigCPtr, this, numToAverage);
  }

  public void setUseRootMeanSquare(boolean useRootMeanSquare) {
    AriaJavaJNI.ArRunningAverage_setUseRootMeanSquare(swigCPtr, this, useRootMeanSquare);
  }

  public boolean getUseRootMeanSquare() {
    return AriaJavaJNI.ArRunningAverage_getUseRootMeanSquare(swigCPtr, this);
  }

  public long getCurrentNumAveraged() {
    return AriaJavaJNI.ArRunningAverage_getCurrentNumAveraged(swigCPtr, this);
  }

}
