/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArRVisionPTZ extends ArPTZ {
  /* (begin code from javabody_derived typemap) */

  private long swigCPtr;

  /* for internal use by swig only */
  public ArRVisionPTZ(long cPtr, boolean cMemoryOwn) {
    super(AriaJavaJNI.SWIGArRVisionPTZUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArRVisionPTZ obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody_derived typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArRVisionPTZ(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ArRVisionPTZ(ArRobot robot) {
    this(AriaJavaJNI.new_ArRVisionPTZ(ArRobot.getCPtr(robot), robot), true);
  }

  public boolean init() {
    return AriaJavaJNI.ArRVisionPTZ_init(swigCPtr, this);
  }

  public boolean pan(double degrees) {
    return AriaJavaJNI.ArRVisionPTZ_pan(swigCPtr, this, degrees);
  }

  public boolean panRel(double degrees) {
    return AriaJavaJNI.ArRVisionPTZ_panRel(swigCPtr, this, degrees);
  }

  public boolean tilt(double degrees) {
    return AriaJavaJNI.ArRVisionPTZ_tilt(swigCPtr, this, degrees);
  }

  public boolean tiltRel(double degrees) {
    return AriaJavaJNI.ArRVisionPTZ_tiltRel(swigCPtr, this, degrees);
  }

  public boolean panTilt(double degreesPan, double degreesTilt) {
    return AriaJavaJNI.ArRVisionPTZ_panTilt(swigCPtr, this, degreesPan, degreesTilt);
  }

  public boolean panTiltRel(double degreesPan, double degreesTilt) {
    return AriaJavaJNI.ArRVisionPTZ_panTiltRel(swigCPtr, this, degreesPan, degreesTilt);
  }

  public boolean canZoom() {
    return AriaJavaJNI.ArRVisionPTZ_canZoom(swigCPtr, this);
  }

  public boolean zoom(int zoomValue) {
    return AriaJavaJNI.ArRVisionPTZ_zoom(swigCPtr, this, zoomValue);
  }

  public boolean zoomRel(int zoomValue) {
    return AriaJavaJNI.ArRVisionPTZ_zoomRel(swigCPtr, this, zoomValue);
  }

  public double getPan() {
    return AriaJavaJNI.ArRVisionPTZ_getPan(swigCPtr, this);
  }

  public double getTilt() {
    return AriaJavaJNI.ArRVisionPTZ_getTilt(swigCPtr, this);
  }

  public int getZoom() {
    return AriaJavaJNI.ArRVisionPTZ_getZoom(swigCPtr, this);
  }

  public double getMaxPosPan() {
    return AriaJavaJNI.ArRVisionPTZ_getMaxPosPan(swigCPtr, this);
  }

  public double getMaxNegPan() {
    return AriaJavaJNI.ArRVisionPTZ_getMaxNegPan(swigCPtr, this);
  }

  public double getMaxPosTilt() {
    return AriaJavaJNI.ArRVisionPTZ_getMaxPosTilt(swigCPtr, this);
  }

  public double getMaxNegTilt() {
    return AriaJavaJNI.ArRVisionPTZ_getMaxNegTilt(swigCPtr, this);
  }

  public int getMaxZoom() {
    return AriaJavaJNI.ArRVisionPTZ_getMaxZoom(swigCPtr, this);
  }

  public int getMinZoom() {
    return AriaJavaJNI.ArRVisionPTZ_getMinZoom(swigCPtr, this);
  }

  public boolean canGetRealPanTilt() {
    return AriaJavaJNI.ArRVisionPTZ_canGetRealPanTilt(swigCPtr, this);
  }

  public boolean canGetRealZoom() {
    return AriaJavaJNI.ArRVisionPTZ_canGetRealZoom(swigCPtr, this);
  }

  public boolean canGetFOV() {
    return AriaJavaJNI.ArRVisionPTZ_canGetFOV(swigCPtr, this);
  }

  public double getFOVAtMaxZoom() {
    return AriaJavaJNI.ArRVisionPTZ_getFOVAtMaxZoom(swigCPtr, this);
  }

  public double getFOVAtMinZoom() {
    return AriaJavaJNI.ArRVisionPTZ_getFOVAtMinZoom(swigCPtr, this);
  }

  public ArBasePacket readPacket() {
    long cPtr = AriaJavaJNI.ArRVisionPTZ_readPacket(swigCPtr, this);
    return (cPtr == 0) ? null : new ArBasePacket(cPtr, false);
  }

  public final static int MAX_PAN = AriaJavaJNI.ArRVisionPTZ_MAX_PAN_get();
  public final static int MIN_PAN = AriaJavaJNI.ArRVisionPTZ_MIN_PAN_get();
  public final static int MIN_TILT = AriaJavaJNI.ArRVisionPTZ_MIN_TILT_get();
  public final static int MAX_TILT = AriaJavaJNI.ArRVisionPTZ_MAX_TILT_get();
  public final static int MIN_ZOOM = AriaJavaJNI.ArRVisionPTZ_MIN_ZOOM_get();
  public final static int MAX_ZOOM = AriaJavaJNI.ArRVisionPTZ_MAX_ZOOM_get();
  public final static int TILT_OFFSET_IN_DEGREES = AriaJavaJNI.ArRVisionPTZ_TILT_OFFSET_IN_DEGREES_get();
  public final static int PAN_OFFSET_IN_DEGREES = AriaJavaJNI.ArRVisionPTZ_PAN_OFFSET_IN_DEGREES_get();

}
