/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArSectors {
  /* (begin code from javabody typemap) */

  private long swigCPtr;
  protected boolean swigCMemOwn;

  /* for internal use by swig only */
  public ArSectors(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArSectors obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArSectors(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ArSectors(int numSectors) {
    this(AriaJavaJNI.new_ArSectors__SWIG_0(numSectors), true);
  }

  public ArSectors() {
    this(AriaJavaJNI.new_ArSectors__SWIG_1(), true);
  }

  public void clear() {
    AriaJavaJNI.ArSectors_clear(swigCPtr, this);
  }

  public void update(double angle) {
    AriaJavaJNI.ArSectors_update(swigCPtr, this, angle);
  }

  public boolean didAll() {
    return AriaJavaJNI.ArSectors_didAll(swigCPtr, this);
  }

}
