/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArSensorReadingVector {
  /* (begin code from javabody typemap) */

  private long swigCPtr;
  protected boolean swigCMemOwn;

  /* for internal use by swig only */
  public ArSensorReadingVector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArSensorReadingVector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArSensorReadingVector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ArSensorReadingVector() {
    this(AriaJavaJNI.new_ArSensorReadingVector__SWIG_0(), true);
  }

  public ArSensorReadingVector(long n) {
    this(AriaJavaJNI.new_ArSensorReadingVector__SWIG_1(n), true);
  }

  public long size() {
    return AriaJavaJNI.ArSensorReadingVector_size(swigCPtr, this);
  }

  public long capacity() {
    return AriaJavaJNI.ArSensorReadingVector_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    AriaJavaJNI.ArSensorReadingVector_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return AriaJavaJNI.ArSensorReadingVector_isEmpty(swigCPtr, this);
  }

  public void clear() {
    AriaJavaJNI.ArSensorReadingVector_clear(swigCPtr, this);
  }

  public void add(ArSensorReading x) {
    AriaJavaJNI.ArSensorReadingVector_add(swigCPtr, this, ArSensorReading.getCPtr(x), x);
  }

  public ArSensorReading get(int i) {
    return new ArSensorReading(AriaJavaJNI.ArSensorReadingVector_get(swigCPtr, this, i), false);
  }

  public void set(int i, ArSensorReading val) {
    AriaJavaJNI.ArSensorReadingVector_set(swigCPtr, this, i, ArSensorReading.getCPtr(val), val);
  }

}
