/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArSimpleConnector {
  /* (begin code from javabody typemap) */

  private long swigCPtr;
  protected boolean swigCMemOwn;

  /* for internal use by swig only */
  public ArSimpleConnector(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArSimpleConnector obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArSimpleConnector(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ArSimpleConnector(java.lang.String[] argc) {
    this(AriaJavaJNI.new_ArSimpleConnector__SWIG_0(argc), true);
  }

  public ArSimpleConnector(ArArgumentBuilder arguments) {
    this(AriaJavaJNI.new_ArSimpleConnector__SWIG_1(ArArgumentBuilder.getCPtr(arguments), arguments), true);
  }

  public ArSimpleConnector(ArArgumentParser parser) {
    this(AriaJavaJNI.new_ArSimpleConnector__SWIG_2(ArArgumentParser.getCPtr(parser), parser), true);
  }

  public boolean setupRobot(ArRobot robot) {
    return AriaJavaJNI.ArSimpleConnector_setupRobot(swigCPtr, this, ArRobot.getCPtr(robot), robot);
  }

  public boolean connectRobot(ArRobot robot) {
    return AriaJavaJNI.ArSimpleConnector_connectRobot(swigCPtr, this, ArRobot.getCPtr(robot), robot);
  }

  public boolean setupLaser(ArSick laser) {
    return AriaJavaJNI.ArSimpleConnector_setupLaser(swigCPtr, this, ArSick.getCPtr(laser), laser);
  }

  public boolean setupSecondLaser(ArSick laser) {
    return AriaJavaJNI.ArSimpleConnector_setupSecondLaser(swigCPtr, this, ArSick.getCPtr(laser), laser);
  }

  public boolean setupLaserArbitrary(ArSick laser, int laserNumber) {
    return AriaJavaJNI.ArSimpleConnector_setupLaserArbitrary(swigCPtr, this, ArSick.getCPtr(laser), laser, laserNumber);
  }

  public boolean connectLaser(ArSick laser) {
    return AriaJavaJNI.ArSimpleConnector_connectLaser(swigCPtr, this, ArSick.getCPtr(laser), laser);
  }

  public boolean connectSecondLaser(ArSick laser) {
    return AriaJavaJNI.ArSimpleConnector_connectSecondLaser(swigCPtr, this, ArSick.getCPtr(laser), laser);
  }

  public boolean connectLaserArbitrary(ArSick laser, int laserNumber) {
    return AriaJavaJNI.ArSimpleConnector_connectLaserArbitrary(swigCPtr, this, ArSick.getCPtr(laser), laser, laserNumber);
  }

  public boolean parseArgs() {
    return AriaJavaJNI.ArSimpleConnector_parseArgs__SWIG_0(swigCPtr, this);
  }

  public boolean parseArgs(ArArgumentParser parser) {
    return AriaJavaJNI.ArSimpleConnector_parseArgs__SWIG_1(swigCPtr, this, ArArgumentParser.getCPtr(parser), parser);
  }

  public void logOptions() {
    AriaJavaJNI.ArSimpleConnector_logOptions(swigCPtr, this);
  }

  public void setMaxNumLasers(int maxNumLasers) {
    AriaJavaJNI.ArSimpleConnector_setMaxNumLasers__SWIG_0(swigCPtr, this, maxNumLasers);
  }

  public void setMaxNumLasers() {
    AriaJavaJNI.ArSimpleConnector_setMaxNumLasers__SWIG_1(swigCPtr, this);
  }

}
