/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArSimulatedLaser extends ArLaser {
  /* (begin code from javabody_derived typemap) */

  private long swigCPtr;

  /* for internal use by swig only */
  public ArSimulatedLaser(long cPtr, boolean cMemoryOwn) {
    super(AriaJavaJNI.SWIGArSimulatedLaserUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArSimulatedLaser obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody_derived typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArSimulatedLaser(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ArSimulatedLaser(ArLaser laser) {
    this(AriaJavaJNI.new_ArSimulatedLaser(ArLaser.getCPtr(laser), laser), true);
  }

  public boolean blockingConnect() {
    return AriaJavaJNI.ArSimulatedLaser_blockingConnect(swigCPtr, this);
  }

  public boolean asyncConnect() {
    return AriaJavaJNI.ArSimulatedLaser_asyncConnect(swigCPtr, this);
  }

  public boolean disconnect() {
    return AriaJavaJNI.ArSimulatedLaser_disconnect(swigCPtr, this);
  }

  public boolean isConnected() {
    return AriaJavaJNI.ArSimulatedLaser_isConnected(swigCPtr, this);
  }

  public boolean isTryingToConnect() {
    return AriaJavaJNI.ArSimulatedLaser_isTryingToConnect(swigCPtr, this);
  }

}
