/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArSonarDevice extends ArRangeDevice {
  /* (begin code from javabody_derived typemap) */

  private long swigCPtr;

  /* for internal use by swig only */
  public ArSonarDevice(long cPtr, boolean cMemoryOwn) {
    super(AriaJavaJNI.SWIGArSonarDeviceUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArSonarDevice obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody_derived typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArSonarDevice(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ArSonarDevice(long currentBufferSize, long cumulativeBufferSize, String name) {
    this(AriaJavaJNI.new_ArSonarDevice__SWIG_0(currentBufferSize, cumulativeBufferSize, name), true);
  }

  public ArSonarDevice(long currentBufferSize, long cumulativeBufferSize) {
    this(AriaJavaJNI.new_ArSonarDevice__SWIG_1(currentBufferSize, cumulativeBufferSize), true);
  }

  public ArSonarDevice(long currentBufferSize) {
    this(AriaJavaJNI.new_ArSonarDevice__SWIG_2(currentBufferSize), true);
  }

  public ArSonarDevice() {
    this(AriaJavaJNI.new_ArSonarDevice__SWIG_3(), true);
  }

  public void processReadings() {
    AriaJavaJNI.ArSonarDevice_processReadings(swigCPtr, this);
  }

  public void setRobot(ArRobot robot) {
    AriaJavaJNI.ArSonarDevice_setRobot(swigCPtr, this, ArRobot.getCPtr(robot), robot);
  }

  public void addReading(double x, double y) {
    AriaJavaJNI.ArSonarDevice_addReading(swigCPtr, this, x, y);
  }

  public void setCumulativeMaxRange(double range) {
    AriaJavaJNI.ArSonarDevice_setCumulativeMaxRange(swigCPtr, this, range);
  }

}
