/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArSoundPlayer {
  /* (begin code from javabody typemap) */

  private long swigCPtr;
  protected boolean swigCMemOwn;

  /* for internal use by swig only */
  public ArSoundPlayer(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArSoundPlayer obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArSoundPlayer(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static boolean playWavFile(String filename, String params) {
    return AriaJavaJNI.ArSoundPlayer_playWavFile(filename, params);
  }

  public static boolean playNativeFile(String filename, String params) {
    return AriaJavaJNI.ArSoundPlayer_playNativeFile(filename, params);
  }

  public static void stopPlaying() {
    AriaJavaJNI.ArSoundPlayer_stopPlaying();
  }

  public static SWIGTYPE_p_ArRetFunctor2T_bool_char_const_p_char_const_p_t getPlayWavFileCallback() {
    long cPtr = AriaJavaJNI.ArSoundPlayer_getPlayWavFileCallback();
    return (cPtr == 0) ? null : new SWIGTYPE_p_ArRetFunctor2T_bool_char_const_p_char_const_p_t(cPtr, false);
  }

  public static ArFunctor getStopPlayingCallback() {
    long cPtr = AriaJavaJNI.ArSoundPlayer_getStopPlayingCallback();
    return (cPtr == 0) ? null : new ArFunctor(cPtr, false);
  }

  public static boolean playSoundPCM16(String data, int numSamples) {
    return AriaJavaJNI.ArSoundPlayer_playSoundPCM16(data, numSamples);
  }

  public ArSoundPlayer() {
    this(AriaJavaJNI.new_ArSoundPlayer(), true);
  }

}
