/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArSpeechSynth {
  /* (begin code from javabody typemap) */

  private long swigCPtr;
  protected boolean swigCMemOwn;

  /* for internal use by swig only */
  public ArSpeechSynth(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArSpeechSynth obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArSpeechSynth(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public boolean init() {
    return AriaJavaJNI.ArSpeechSynth_init(swigCPtr, this);
  }

  public void addToConfig(ArConfig config) {
    AriaJavaJNI.ArSpeechSynth_addToConfig(swigCPtr, this, ArConfig.getCPtr(config), config);
  }

  public boolean speak(String str, String voiceParams, SWIGTYPE_p_ArRetFunctor2T_bool_short_p_int_t audioOutputCB, int sampleRate) {
    return AriaJavaJNI.ArSpeechSynth_speak__SWIG_0(swigCPtr, this, str, voiceParams, SWIGTYPE_p_ArRetFunctor2T_bool_short_p_int_t.getCPtr(audioOutputCB), sampleRate);
  }

  public boolean speak(String str, String voiceParams, SWIGTYPE_p_ArRetFunctor2T_bool_short_p_int_t audioOutputCB) {
    return AriaJavaJNI.ArSpeechSynth_speak__SWIG_1(swigCPtr, this, str, voiceParams, SWIGTYPE_p_ArRetFunctor2T_bool_short_p_int_t.getCPtr(audioOutputCB));
  }

  public boolean speak(String str, String voiceParams) {
    return AriaJavaJNI.ArSpeechSynth_speak__SWIG_2(swigCPtr, this, str, voiceParams);
  }

  public boolean speak(String str) {
    return AriaJavaJNI.ArSpeechSynth_speak__SWIG_3(swigCPtr, this, str);
  }

  public boolean speakf(String fmt) {
    return AriaJavaJNI.ArSpeechSynth_speakf(swigCPtr, this, fmt);
  }

  public void interrupt() {
    AriaJavaJNI.ArSpeechSynth_interrupt(swigCPtr, this);
  }

  public SWIGTYPE_p_ArRetFunctorCT_bool_ArSpeechSynth_t getInitCallback() {
    long cPtr = AriaJavaJNI.ArSpeechSynth_getInitCallback(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_ArRetFunctorCT_bool_ArSpeechSynth_t(cPtr, false);
  }

  public SWIGTYPE_p_ArRetFunctor2CT_bool_ArSpeechSynth_char_const_p_char_const_p_t getSpeakCallback() {
    long cPtr = AriaJavaJNI.ArSpeechSynth_getSpeakCallback(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_ArRetFunctor2CT_bool_ArSpeechSynth_char_const_p_char_const_p_t(cPtr, false);
  }

  public SWIGTYPE_p_ArFunctorCT_ArSpeechSynth_t getInterruptCallback() {
    long cPtr = AriaJavaJNI.ArSpeechSynth_getInterruptCallback(swigCPtr, this);
    return (cPtr == 0) ? null : new SWIGTYPE_p_ArFunctorCT_ArSpeechSynth_t(cPtr, false);
  }

  public void setAudioCallback(SWIGTYPE_p_ArRetFunctor2T_bool_short_p_int_t cb) {
    AriaJavaJNI.ArSpeechSynth_setAudioCallback(swigCPtr, this, SWIGTYPE_p_ArRetFunctor2T_bool_short_p_int_t.getCPtr(cb));
  }

  public void setAudioSampleRate(int rate) {
    AriaJavaJNI.ArSpeechSynth_setAudioSampleRate(swigCPtr, this, rate);
  }

  public int getAudioSampleRate() {
    return AriaJavaJNI.ArSpeechSynth_getAudioSampleRate(swigCPtr, this);
  }

  public void lock() {
    AriaJavaJNI.ArSpeechSynth_lock(swigCPtr, this);
  }

  public void unlock() {
    AriaJavaJNI.ArSpeechSynth_unlock(swigCPtr, this);
  }

  public boolean setVoice(String name) {
    return AriaJavaJNI.ArSpeechSynth_setVoice(swigCPtr, this, name);
  }

  public String getCurrentVoiceName() {
    return AriaJavaJNI.ArSpeechSynth_getCurrentVoiceName(swigCPtr, this);
  }

  public SWIGTYPE_p_std__listT_std__string_t getVoiceNames() {
    return new SWIGTYPE_p_std__listT_std__string_t(AriaJavaJNI.ArSpeechSynth_getVoiceNames(swigCPtr, this), true);
  }

}
