/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArStringInfoHolderFunctions {
  /* (begin code from javabody typemap) */

  private long swigCPtr;
  protected boolean swigCMemOwn;

  /* for internal use by swig only */
  public ArStringInfoHolderFunctions(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArStringInfoHolderFunctions obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArStringInfoHolderFunctions(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public static void intWrapper(String buffer, int bufferLen, ArRetFunctor_Int functor, String format) {
    AriaJavaJNI.ArStringInfoHolderFunctions_intWrapper(buffer, bufferLen, ArRetFunctor_Int.getCPtr(functor), functor, format);
  }

  public static void doubleWrapper(String buffer, int bufferLen, ArRetFunctor_Double functor, String format) {
    AriaJavaJNI.ArStringInfoHolderFunctions_doubleWrapper(buffer, bufferLen, ArRetFunctor_Double.getCPtr(functor), functor, format);
  }

  public static void boolWrapper(String buffer, int bufferLen, ArRetFunctor_Bool functor, String format) {
    AriaJavaJNI.ArStringInfoHolderFunctions_boolWrapper(buffer, bufferLen, ArRetFunctor_Bool.getCPtr(functor), functor, format);
  }

  public static void stringWrapper(String buffer, int bufferLen, SWIGTYPE_p_ArRetFunctorT_char_const_p_t functor, String format) {
    AriaJavaJNI.ArStringInfoHolderFunctions_stringWrapper(buffer, bufferLen, SWIGTYPE_p_ArRetFunctorT_char_const_p_t.getCPtr(functor), format);
  }

  public static void unsignedLongWrapper(String buffer, int bufferLen, SWIGTYPE_p_ArRetFunctorT_unsigned_long_t functor, String format) {
    AriaJavaJNI.ArStringInfoHolderFunctions_unsignedLongWrapper(buffer, bufferLen, SWIGTYPE_p_ArRetFunctorT_unsigned_long_t.getCPtr(functor), format);
  }

  public ArStringInfoHolderFunctions() {
    this(AriaJavaJNI.new_ArStringInfoHolderFunctions(), true);
  }

}
