/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArSyncLoop extends ArASyncTask {
  /* (begin code from javabody_derived typemap) */

  private long swigCPtr;

  /* for internal use by swig only */
  public ArSyncLoop(long cPtr, boolean cMemoryOwn) {
    super(AriaJavaJNI.SWIGArSyncLoopUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArSyncLoop obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody_derived typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArSyncLoop(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ArSyncLoop() {
    this(AriaJavaJNI.new_ArSyncLoop(), true);
  }

  public void setRobot(ArRobot robot) {
    AriaJavaJNI.ArSyncLoop_setRobot(swigCPtr, this, ArRobot.getCPtr(robot), robot);
  }

  public void stopRunIfNotConnected(boolean stopRun) {
    AriaJavaJNI.ArSyncLoop_stopRunIfNotConnected(swigCPtr, this, stopRun);
  }

  public SWIGTYPE_p_void runThread(SWIGTYPE_p_void arg) {
    long cPtr = AriaJavaJNI.ArSyncLoop_runThread(swigCPtr, this, SWIGTYPE_p_void.getCPtr(arg));
    return (cPtr == 0) ? null : new SWIGTYPE_p_void(cPtr, false);
  }

  public String getThreadActivity() {
    return AriaJavaJNI.ArSyncLoop_getThreadActivity(swigCPtr, this);
  }

}
