/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArTCMCompassRobot extends ArTCM2 {
  /* (begin code from javabody_derived typemap) */

  private long swigCPtr;

  /* for internal use by swig only */
  public ArTCMCompassRobot(long cPtr, boolean cMemoryOwn) {
    super(AriaJavaJNI.SWIGArTCMCompassRobotUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArTCMCompassRobot obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody_derived typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArTCMCompassRobot(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ArTCMCompassRobot(ArRobot robot) {
    this(AriaJavaJNI.new_ArTCMCompassRobot(ArRobot.getCPtr(robot), robot), true);
  }

  public void commandOff() {
    AriaJavaJNI.ArTCMCompassRobot_commandOff(swigCPtr, this);
  }

  public void commandJustCompass() {
    AriaJavaJNI.ArTCMCompassRobot_commandJustCompass(swigCPtr, this);
  }

  public void commandOnePacket() {
    AriaJavaJNI.ArTCMCompassRobot_commandOnePacket(swigCPtr, this);
  }

  public void commandContinuousPackets() {
    AriaJavaJNI.ArTCMCompassRobot_commandContinuousPackets(swigCPtr, this);
  }

  public void commandUserCalibration() {
    AriaJavaJNI.ArTCMCompassRobot_commandUserCalibration(swigCPtr, this);
  }

  public void commandAutoCalibration() {
    AriaJavaJNI.ArTCMCompassRobot_commandAutoCalibration(swigCPtr, this);
  }

  public void commandStopCalibration() {
    AriaJavaJNI.ArTCMCompassRobot_commandStopCalibration(swigCPtr, this);
  }

  public void commandSoftReset() {
    AriaJavaJNI.ArTCMCompassRobot_commandSoftReset(swigCPtr, this);
  }

}
