/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArUrg extends ArLaser {
  /* (begin code from javabody_derived typemap) */

  private long swigCPtr;

  /* for internal use by swig only */
  public ArUrg(long cPtr, boolean cMemoryOwn) {
    super(AriaJavaJNI.SWIGArUrgUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArUrg obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody_derived typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArUrg(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ArUrg(int laserNumber, String name) {
    this(AriaJavaJNI.new_ArUrg__SWIG_0(laserNumber, name), true);
  }

  public ArUrg(int laserNumber) {
    this(AriaJavaJNI.new_ArUrg__SWIG_1(laserNumber), true);
  }

  public boolean blockingConnect() {
    return AriaJavaJNI.ArUrg_blockingConnect(swigCPtr, this);
  }

  public boolean asyncConnect() {
    return AriaJavaJNI.ArUrg_asyncConnect(swigCPtr, this);
  }

  public boolean disconnect() {
    return AriaJavaJNI.ArUrg_disconnect(swigCPtr, this);
  }

  public boolean isConnected() {
    return AriaJavaJNI.ArUrg_isConnected(swigCPtr, this);
  }

  public boolean isTryingToConnect() {
    return AriaJavaJNI.ArUrg_isTryingToConnect(swigCPtr, this);
  }

  public void log() {
    AriaJavaJNI.ArUrg_log(swigCPtr, this);
  }

}
