/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArVCC4Packet extends ArBasePacket {
  /* (begin code from javabody_derived typemap) */

  private long swigCPtr;

  /* for internal use by swig only */
  public ArVCC4Packet(long cPtr, boolean cMemoryOwn) {
    super(AriaJavaJNI.SWIGArVCC4PacketUpcast(cPtr), cMemoryOwn);
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArVCC4Packet obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody_derived typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArVCC4Packet(swigCPtr);
      }
      swigCPtr = 0;
    }
    super.delete();
  }

  public ArVCC4Packet(int bufferSize) {
    this(AriaJavaJNI.new_ArVCC4Packet__SWIG_0(bufferSize), true);
  }

  public ArVCC4Packet() {
    this(AriaJavaJNI.new_ArVCC4Packet__SWIG_1(), true);
  }

  public void byte2ToBuf(int val) {
    AriaJavaJNI.ArVCC4Packet_byte2ToBuf(swigCPtr, this, val);
  }

  public void finalizePacket() {
    AriaJavaJNI.ArVCC4Packet_finalizePacket(swigCPtr, this);
  }

}
