/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class ArWGS84 {
  /* (begin code from javabody typemap) */

  private long swigCPtr;
  protected boolean swigCMemOwn;

  /* for internal use by swig only */
  public ArWGS84(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(ArWGS84 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_ArWGS84(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ArWGS84() {
    this(AriaJavaJNI.new_ArWGS84(), true);
  }

  public static double getE() {
    return AriaJavaJNI.ArWGS84_getE();
  }

  public static double getA() {
    return AriaJavaJNI.ArWGS84_getA();
  }

  public static double getB() {
    return AriaJavaJNI.ArWGS84_getB();
  }

  public static double getEP() {
    return AriaJavaJNI.ArWGS84_getEP();
  }

  public static double get1byf() {
    return AriaJavaJNI.ArWGS84_get1byf();
  }

  public static double getOmega() {
    return AriaJavaJNI.ArWGS84_getOmega();
  }

  public static double getGM() {
    return AriaJavaJNI.ArWGS84_getGM();
  }

}
