/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class IntArPoseMap {
  /* (begin code from javabody typemap) */

  private long swigCPtr;
  protected boolean swigCMemOwn;

  /* for internal use by swig only */
  public IntArPoseMap(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  /* for internal use by swig only */
  public static long getCPtr(IntArPoseMap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody typemap) */

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        AriaJavaJNI.delete_IntArPoseMap(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public IntArPoseMap() {
    this(AriaJavaJNI.new_IntArPoseMap__SWIG_0(), true);
  }

  public IntArPoseMap(IntArPoseMap arg0) {
    this(AriaJavaJNI.new_IntArPoseMap__SWIG_1(IntArPoseMap.getCPtr(arg0), arg0), true);
  }

  public long size() {
    return AriaJavaJNI.IntArPoseMap_size(swigCPtr, this);
  }

  public boolean empty() {
    return AriaJavaJNI.IntArPoseMap_empty(swigCPtr, this);
  }

  public void clear() {
    AriaJavaJNI.IntArPoseMap_clear(swigCPtr, this);
  }

  public ArPose get(int key) {
    return new ArPose(AriaJavaJNI.IntArPoseMap_get(swigCPtr, this, key), false);
  }

  public void set(int key, ArPose x) {
    AriaJavaJNI.IntArPoseMap_set(swigCPtr, this, key, ArPose.getCPtr(x), x);
  }

  public void del(int key) {
    AriaJavaJNI.IntArPoseMap_del(swigCPtr, this, key);
  }

  public boolean has_key(int key) {
    return AriaJavaJNI.IntArPoseMap_has_key(swigCPtr, this, key);
  }

}
