/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 1.3.40
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.mobilerobots.Aria;

public class SWIGTYPE_p_ArRetFunctor2T_bool_char_const_p_char_const_p_t {
  /* (begin code from javabody typemap for pointers, references, and arrays) */

  private long swigCPtr;

  /* for internal use by swig only */
  public SWIGTYPE_p_ArRetFunctor2T_bool_char_const_p_char_const_p_t(long cPtr, boolean bFutureUse) {
    swigCPtr = cPtr;
  }

  protected SWIGTYPE_p_ArRetFunctor2T_bool_char_const_p_char_const_p_t() {
    swigCPtr = 0;
  }

  /* for internal use by swig only */
  public static long getCPtr(SWIGTYPE_p_ArRetFunctor2T_bool_char_const_p_char_const_p_t obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  /* (end code from javabody typemap for pointers, references, and arrays) */
}

